
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            planOptions = NULL,
            presetDV = "Blank",
            presetIV = "Blank",
            presetIV2 = "none",
            presetWorld = "simple",
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 0,
            DVnlevs = 7,
            DViqr = 4,
            DVncats = 2,
            DVcases = "C1,C2",
            DVprops = "1,1",
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 0,
            IVnlevs = 7,
            IViqr = 4,
            IVncats = 2,
            IVcases = "C1,C2",
            IVprops = "1,1",
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 0,
            IV2nlevs = 7,
            IV2iqr = 4,
            IV2ncats = 2,
            IV2cases = "C1,C2",
            IV2props = "1,1",
            EffectSize1 = 0,
            EffectSize2 = 0,
            EffectSize3 = 0,
            EffectSize12 = 0,
            EffectConfig = "normal",
            Heteroscedasticity = 0,
            Residuals = "normal",
            WorldOn = FALSE,
            WorldPDF = "Single",
            WorldRZ = NULL,
            WorldLambda = 0.3,
            WorldNullP = 0.5,
            SampleSize = 42,
            SampleSizeM = 42,
            SampleSpreadOn = FALSE,
            SampleGamma = 1.56,
            SampleMethod = "Random",
            SampleUsage1 = "Between",
            SampleUsage2 = "Between",
            Dependence = 0,
            Outliers = 0,
            NonResponse = 0,
            LimitRange = "no",
            RangeMin = -3,
            RangeMax = 3,
            Cheating = "None",
            CheatingAttempts = 5,
            ReplicationOn = FALSE,
            ReplicationPower = 0.8,
            ReplicationPrior = "None",
            ReplicationAttempts = 1,
            ReplicationDecision = "Cautious",
            ReplicationAlpha = 0.05,
            ReplicationSign = "yes",
            ReplicationSigOriginal = "yes",
            alphaSig = 0.05,
            ssq = "Type3",
            interaction = "no",
            equalVar = "yes",
            Transform = "None",
            likelihoodType = "Populations",
            likelihoodCutaway = "cutaway",
            likelihoodUsePrior = "none",
            priorPDF = "Exp",
            priorRZ = "z",
            priorLambda = 0.3,
            priorNullP = 0,
            MetaAnalysisOn = FALSE,
            MetaAnalysisType = "random",
            MetaAnalysisNulls = "yes",
            MetaAnalysisBias = "yes",
            MetaAnalysisNStudies = 10,
            MetaAnalysisStudiesSig = "sigOnly",
            showHypothesisBtn = NULL,
            makeSampleBtn = FALSE,
            numberSamples = 100,
            makeMultipleBtn = NULL,
            inferVar1 = "rs",
            inferVar2 = "p",
            showSampleType = "Compact",
            showInferDimension = "1D",
            reportInferStats = "Medians",
            showMultipleParam = "Basic",
            showMultipleDimension = "1D",
            exploreNPointsH = 13,
            exploreNPointsD = 13,
            exploreNPointsA = 13,
            exploreNPointsM = 13,
            exploreMinValH = "-0.9",
            exploreMaxValH = "0.9",
            exploreMinValD = "10",
            exploreMaxValD = "250",
            exploreMinValA = "0.001",
            exploreMaxValM = "0.5",
            exploreMinValM = "0.001",
            exploreMaxValA = "0.5",
            exploreXLogH = FALSE,
            exploreXLogD = FALSE,
            exploreXLogA = FALSE,
            exploreXLogM = FALSE,
            numberExplores = 10,
            makeExploreBtn = NULL,
            exploreMode = "designExplore",
            hypothesisExploreList = NULL,
            designExploreList = NULL,
            analysisExploreList = NULL,
            moreExploreList = NULL,
            showExploreParam = "Basic",
            showExploreDimension = "1D",
            whichShowMultiple = "all",
            jamoviHelp = FALSE,
            brawHelp = TRUE,
            demoHelp = TRUE,
            demoWhich = "blank",
            showHTML = FALSE,
            doProject1sBtn = NULL,
            doProject1aBtn = NULL,
            doProject1bBtn = NULL,
            doProject1cLst = "Perfectionism",
            doProject1cLstA = "ExamGrade",
            doProject1cBtn = NULL,
            doProject2aBtn = NULL,
            doProject2bBtn = NULL,
            doProject2cBtn = NULL,
            doProject2dBtn = NULL,
            doProject3aBtn = NULL,
            doProject3bBtn = NULL,
            doProject3cBtn = NULL,
            doProject3dBtn = NULL,
            doProject4aBtn = NULL,
            doProject4bBtn = NULL,
            doProject4cBtn = NULL,
            doProject4dBtn = NULL,
            doProject5sBtn = NULL,
            doProject5aBtn = NULL,
            doProject5bBtn = NULL,
            doProject5cBtn = NULL,
            doProject5dBtn = NULL,
            doproject6sBtn = NULL,
            doproject6aBtn = NULL,
            doproject6bBtn = NULL,
            doproject6bLst = "n42",
            doproject6cBtn = NULL,
            doproject6dBtn = NULL,
            doproject6dLst = "r03",
            doproject7sBtn = NULL,
            doproject7sLst = "iii",
            doproject7aBtn = NULL,
            doproject7aLst = "r03",
            doproject7bBtn = NULL,
            doproject7bLst = "r03",
            doproject7cBtn = NULL,
            doproject7cLst = "r03",
            doproject7dBtn = NULL,
            doproject8aBtn = NULL,
            doproject8aLst = "iii",
            doproject8bBtn = NULL,
            doproject8bLst = "r03",
            doproject8cBtn = NULL,
            doproject8cLst = "r03",
            doProject9sBtn = NULL,
            doproject9aBtn = NULL,
            doproject9bBtn = NULL,
            doproject9bLst = "r03",
            doproject9cBtn = NULL,
            doProject10sBtn = NULL,
            doproject10aBtn = NULL,
            doproject10bBtn = NULL,
            doproject10bLst = "r03",
            doproject10cBtn = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..planOptions <- jmvcore::OptionList$new(
                "planOptions",
                planOptions,
                options=list(
                    "planH",
                    "planD",
                    "planA",
                    "planM"))
            private$..presetDV <- jmvcore::OptionList$new(
                "presetDV",
                presetDV,
                options=list(
                    "Blank",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "ExamGrade",
                    "ExamPass",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="Blank")
            private$..presetIV <- jmvcore::OptionList$new(
                "presetIV",
                presetIV,
                options=list(
                    "Blank",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="Blank")
            private$..presetIV2 <- jmvcore::OptionList$new(
                "presetIV2",
                presetIV2,
                options=list(
                    "none",
                    "IV2",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="none")
            private$..presetWorld <- jmvcore::OptionList$new(
                "presetWorld",
                presetWorld,
                options=list(
                    "psych",
                    "simple"),
                default="simple")
            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=0)
            private$..DVnlevs <- jmvcore::OptionNumber$new(
                "DVnlevs",
                DVnlevs,
                default=7)
            private$..DViqr <- jmvcore::OptionNumber$new(
                "DViqr",
                DViqr,
                default=4)
            private$..DVncats <- jmvcore::OptionNumber$new(
                "DVncats",
                DVncats,
                default=2)
            private$..DVcases <- jmvcore::OptionString$new(
                "DVcases",
                DVcases,
                default="C1,C2")
            private$..DVprops <- jmvcore::OptionString$new(
                "DVprops",
                DVprops,
                default="1,1")
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=0)
            private$..IVnlevs <- jmvcore::OptionNumber$new(
                "IVnlevs",
                IVnlevs,
                default=7)
            private$..IViqr <- jmvcore::OptionNumber$new(
                "IViqr",
                IViqr,
                default=4)
            private$..IVncats <- jmvcore::OptionNumber$new(
                "IVncats",
                IVncats,
                default=2)
            private$..IVcases <- jmvcore::OptionString$new(
                "IVcases",
                IVcases,
                default="C1,C2")
            private$..IVprops <- jmvcore::OptionString$new(
                "IVprops",
                IVprops,
                default="1,1")
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=0)
            private$..IV2nlevs <- jmvcore::OptionNumber$new(
                "IV2nlevs",
                IV2nlevs,
                default=7)
            private$..IV2iqr <- jmvcore::OptionNumber$new(
                "IV2iqr",
                IV2iqr,
                default=4)
            private$..IV2ncats <- jmvcore::OptionNumber$new(
                "IV2ncats",
                IV2ncats,
                default=2)
            private$..IV2cases <- jmvcore::OptionString$new(
                "IV2cases",
                IV2cases,
                default="C1,C2")
            private$..IV2props <- jmvcore::OptionString$new(
                "IV2props",
                IV2props,
                default="1,1")
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0)
            private$..EffectConfig <- jmvcore::OptionList$new(
                "EffectConfig",
                EffectConfig,
                options=list(
                    "simple",
                    "normal",
                    "path"),
                default="normal")
            private$..Heteroscedasticity <- jmvcore::OptionNumber$new(
                "Heteroscedasticity",
                Heteroscedasticity,
                default=0)
            private$..Residuals <- jmvcore::OptionList$new(
                "Residuals",
                Residuals,
                options=list(
                    "normal",
                    "skewed",
                    "uniform",
                    "cauchy"),
                default="normal")
            private$..WorldOn <- jmvcore::OptionBool$new(
                "WorldOn",
                WorldOn,
                default=FALSE)
            private$..WorldPDF <- jmvcore::OptionList$new(
                "WorldPDF",
                WorldPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Single")
            private$..WorldRZ <- jmvcore::OptionList$new(
                "WorldRZ",
                WorldRZ,
                options=list(
                    "r",
                    "z"))
            private$..WorldLambda <- jmvcore::OptionNumber$new(
                "WorldLambda",
                WorldLambda,
                default=0.3)
            private$..WorldNullP <- jmvcore::OptionNumber$new(
                "WorldNullP",
                WorldNullP,
                default=0.5)
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleSizeM <- jmvcore::OptionNumber$new(
                "SampleSizeM",
                SampleSizeM,
                default=42)
            private$..SampleSpreadOn <- jmvcore::OptionBool$new(
                "SampleSpreadOn",
                SampleSpreadOn,
                default=FALSE)
            private$..SampleGamma <- jmvcore::OptionNumber$new(
                "SampleGamma",
                SampleGamma,
                default=1.56)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Cluster",
                    "Snowball",
                    "Convenience"),
                default="Random")
            private$..SampleUsage1 <- jmvcore::OptionList$new(
                "SampleUsage1",
                SampleUsage1,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..SampleUsage2 <- jmvcore::OptionList$new(
                "SampleUsage2",
                SampleUsage2,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..NonResponse <- jmvcore::OptionNumber$new(
                "NonResponse",
                NonResponse,
                default=0)
            private$..LimitRange <- jmvcore::OptionList$new(
                "LimitRange",
                LimitRange,
                options=list(
                    "yes",
                    "no"),
                default="no")
            private$..RangeMin <- jmvcore::OptionNumber$new(
                "RangeMin",
                RangeMin,
                default=-3)
            private$..RangeMax <- jmvcore::OptionNumber$new(
                "RangeMax",
                RangeMax,
                default=3)
            private$..Cheating <- jmvcore::OptionList$new(
                "Cheating",
                Cheating,
                options=list(
                    "None",
                    "Grow",
                    "Prune",
                    "Replace",
                    "Retry"),
                default="None")
            private$..CheatingAttempts <- jmvcore::OptionNumber$new(
                "CheatingAttempts",
                CheatingAttempts,
                default=5)
            private$..ReplicationOn <- jmvcore::OptionBool$new(
                "ReplicationOn",
                ReplicationOn,
                default=FALSE)
            private$..ReplicationPower <- jmvcore::OptionNumber$new(
                "ReplicationPower",
                ReplicationPower,
                default=0.8)
            private$..ReplicationPrior <- jmvcore::OptionList$new(
                "ReplicationPrior",
                ReplicationPrior,
                options=list(
                    "None",
                    "World",
                    "Prior"),
                default="None")
            private$..ReplicationAttempts <- jmvcore::OptionNumber$new(
                "ReplicationAttempts",
                ReplicationAttempts,
                default=1)
            private$..ReplicationDecision <- jmvcore::OptionList$new(
                "ReplicationDecision",
                ReplicationDecision,
                options=list(
                    "Cautious",
                    "Last",
                    "FirstSuccess",
                    "Median",
                    "SmallP",
                    "LargeN"),
                default="Cautious")
            private$..ReplicationAlpha <- jmvcore::OptionNumber$new(
                "ReplicationAlpha",
                ReplicationAlpha,
                default=0.05)
            private$..ReplicationSign <- jmvcore::OptionList$new(
                "ReplicationSign",
                ReplicationSign,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..ReplicationSigOriginal <- jmvcore::OptionList$new(
                "ReplicationSigOriginal",
                ReplicationSigOriginal,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..alphaSig <- jmvcore::OptionNumber$new(
                "alphaSig",
                alphaSig,
                default=0.05)
            private$..ssq <- jmvcore::OptionList$new(
                "ssq",
                ssq,
                options=list(
                    "Type1",
                    "Type2",
                    "Type3"),
                default="Type3")
            private$..interaction <- jmvcore::OptionList$new(
                "interaction",
                interaction,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..equalVar <- jmvcore::OptionList$new(
                "equalVar",
                equalVar,
                options=list(
                    "no",
                    "yes"),
                default="yes")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..likelihoodType <- jmvcore::OptionList$new(
                "likelihoodType",
                likelihoodType,
                options=list(
                    "Samples",
                    "Populations"),
                default="Populations")
            private$..likelihoodCutaway <- jmvcore::OptionList$new(
                "likelihoodCutaway",
                likelihoodCutaway,
                options=list(
                    "all",
                    "cutaway"),
                default="cutaway")
            private$..likelihoodUsePrior <- jmvcore::OptionList$new(
                "likelihoodUsePrior",
                likelihoodUsePrior,
                options=list(
                    "none",
                    "world",
                    "prior"),
                default="none")
            private$..priorPDF <- jmvcore::OptionList$new(
                "priorPDF",
                priorPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Exp")
            private$..priorRZ <- jmvcore::OptionList$new(
                "priorRZ",
                priorRZ,
                options=list(
                    "r",
                    "z"),
                default="z")
            private$..priorLambda <- jmvcore::OptionNumber$new(
                "priorLambda",
                priorLambda,
                default=0.3)
            private$..priorNullP <- jmvcore::OptionNumber$new(
                "priorNullP",
                priorNullP,
                default=0)
            private$..MetaAnalysisOn <- jmvcore::OptionBool$new(
                "MetaAnalysisOn",
                MetaAnalysisOn,
                default=FALSE)
            private$..MetaAnalysisType <- jmvcore::OptionList$new(
                "MetaAnalysisType",
                MetaAnalysisType,
                options=list(
                    "random",
                    "fixed"),
                default="random")
            private$..MetaAnalysisNulls <- jmvcore::OptionList$new(
                "MetaAnalysisNulls",
                MetaAnalysisNulls,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..MetaAnalysisBias <- jmvcore::OptionList$new(
                "MetaAnalysisBias",
                MetaAnalysisBias,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..MetaAnalysisNStudies <- jmvcore::OptionNumber$new(
                "MetaAnalysisNStudies",
                MetaAnalysisNStudies,
                default=10)
            private$..MetaAnalysisStudiesSig <- jmvcore::OptionList$new(
                "MetaAnalysisStudiesSig",
                MetaAnalysisStudiesSig,
                options=list(
                    "all",
                    "sigOnly"),
                default="sigOnly")
            private$..showHypothesisBtn <- jmvcore::OptionAction$new(
                "showHypothesisBtn",
                showHypothesisBtn)
            private$..makeSampleBtn <- jmvcore::OptionAction$new(
                "makeSampleBtn",
                makeSampleBtn,
                default=FALSE)
            private$..numberSamples <- jmvcore::OptionNumber$new(
                "numberSamples",
                numberSamples,
                default=100)
            private$..makeMultipleBtn <- jmvcore::OptionAction$new(
                "makeMultipleBtn",
                makeMultipleBtn)
            private$..inferVar1 <- jmvcore::OptionList$new(
                "inferVar1",
                inferVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..inferVar2 <- jmvcore::OptionList$new(
                "inferVar2",
                inferVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..showSampleType <- jmvcore::OptionList$new(
                "showSampleType",
                showSampleType,
                options=list(
                    "Compact",
                    "Variables",
                    "Sample",
                    "Describe",
                    "Infer",
                    "Likelihood"),
                default="Compact")
            private$..showInferDimension <- jmvcore::OptionList$new(
                "showInferDimension",
                showInferDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..reportInferStats <- jmvcore::OptionList$new(
                "reportInferStats",
                reportInferStats,
                options=list(
                    "Means",
                    "Medians"),
                default="Medians")
            private$..showMultipleParam <- jmvcore::OptionList$new(
                "showMultipleParam",
                showMultipleParam,
                options=list(
                    "Basic",
                    "p(sig)",
                    "NHST",
                    "Hits",
                    "Misses",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..showMultipleDimension <- jmvcore::OptionList$new(
                "showMultipleDimension",
                showMultipleDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..exploreNPointsH <- jmvcore::OptionNumber$new(
                "exploreNPointsH",
                exploreNPointsH,
                default=13)
            private$..exploreNPointsD <- jmvcore::OptionNumber$new(
                "exploreNPointsD",
                exploreNPointsD,
                default=13)
            private$..exploreNPointsA <- jmvcore::OptionNumber$new(
                "exploreNPointsA",
                exploreNPointsA,
                default=13)
            private$..exploreNPointsM <- jmvcore::OptionNumber$new(
                "exploreNPointsM",
                exploreNPointsM,
                default=13)
            private$..exploreMinValH <- jmvcore::OptionString$new(
                "exploreMinValH",
                exploreMinValH,
                default="-0.9")
            private$..exploreMaxValH <- jmvcore::OptionString$new(
                "exploreMaxValH",
                exploreMaxValH,
                default="0.9")
            private$..exploreMinValD <- jmvcore::OptionString$new(
                "exploreMinValD",
                exploreMinValD,
                default="10")
            private$..exploreMaxValD <- jmvcore::OptionString$new(
                "exploreMaxValD",
                exploreMaxValD,
                default="250")
            private$..exploreMinValA <- jmvcore::OptionString$new(
                "exploreMinValA",
                exploreMinValA,
                default="0.001")
            private$..exploreMaxValM <- jmvcore::OptionString$new(
                "exploreMaxValM",
                exploreMaxValM,
                default="0.5")
            private$..exploreMinValM <- jmvcore::OptionString$new(
                "exploreMinValM",
                exploreMinValM,
                default="0.001")
            private$..exploreMaxValA <- jmvcore::OptionString$new(
                "exploreMaxValA",
                exploreMaxValA,
                default="0.5")
            private$..exploreXLogH <- jmvcore::OptionBool$new(
                "exploreXLogH",
                exploreXLogH,
                default=FALSE)
            private$..exploreXLogD <- jmvcore::OptionBool$new(
                "exploreXLogD",
                exploreXLogD,
                default=FALSE)
            private$..exploreXLogA <- jmvcore::OptionBool$new(
                "exploreXLogA",
                exploreXLogA,
                default=FALSE)
            private$..exploreXLogM <- jmvcore::OptionBool$new(
                "exploreXLogM",
                exploreXLogM,
                default=FALSE)
            private$..numberExplores <- jmvcore::OptionNumber$new(
                "numberExplores",
                numberExplores,
                default=10)
            private$..makeExploreBtn <- jmvcore::OptionAction$new(
                "makeExploreBtn",
                makeExploreBtn)
            private$..exploreMode <- jmvcore::OptionList$new(
                "exploreMode",
                exploreMode,
                options=list(
                    "hypothesisExplore",
                    "designExplore",
                    "analysisExplore",
                    "moreExplore"),
                default="designExplore")
            private$..hypothesisExploreList <- jmvcore::OptionList$new(
                "hypothesisExploreList",
                hypothesisExploreList,
                options=list(
                    "rIV",
                    "rIVIV2",
                    "rIVIV2DV",
                    "Heteroscedasticity",
                    "blank0h",
                    "IVType",
                    "IVskew",
                    "IVkurtosis",
                    "IVlevels",
                    "IVcats",
                    "IVprops",
                    "DVType",
                    "DVskew",
                    "DVkurtosis",
                    "DVcats",
                    "DVprops",
                    "blank1h",
                    "lambda",
                    "pNull",
                    "blank2h"))
            private$..designExploreList <- jmvcore::OptionList$new(
                "designExploreList",
                designExploreList,
                options=list(
                    "n",
                    "Method",
                    "Usage",
                    "blank1d",
                    "Dependence",
                    "Outliers",
                    "NonResponse",
                    "IVRangeC",
                    "IVRangeE",
                    "blank1e",
                    "Cheating",
                    "CheatingAmount"))
            private$..analysisExploreList <- jmvcore::OptionList$new(
                "analysisExploreList",
                analysisExploreList,
                options=list(
                    "Alpha",
                    "Transform",
                    "Welch",
                    "InteractionOn"))
            private$..moreExploreList <- jmvcore::OptionList$new(
                "moreExploreList",
                moreExploreList,
                options=list(
                    "Power",
                    "Keep",
                    "Repeats"))
            private$..showExploreParam <- jmvcore::OptionList$new(
                "showExploreParam",
                showExploreParam,
                options=list(
                    "Single",
                    "Basic",
                    "p(sig)",
                    "NHST",
                    "Hits",
                    "Misses",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..showExploreDimension <- jmvcore::OptionList$new(
                "showExploreDimension",
                showExploreDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..whichShowMultiple <- jmvcore::OptionList$new(
                "whichShowMultiple",
                whichShowMultiple,
                options=list(
                    "direct",
                    "unique",
                    "total",
                    "all"),
                default="all")
            private$..sendSample <- jmvcore::OptionOutput$new(
                "sendSample")
            private$..sendMultiple <- jmvcore::OptionOutput$new(
                "sendMultiple")
            private$..jamoviHelp <- jmvcore::OptionBool$new(
                "jamoviHelp",
                jamoviHelp,
                default=FALSE)
            private$..brawHelp <- jmvcore::OptionBool$new(
                "brawHelp",
                brawHelp,
                default=TRUE)
            private$..demoHelp <- jmvcore::OptionBool$new(
                "demoHelp",
                demoHelp,
                default=TRUE)
            private$..demoWhich <- jmvcore::OptionList$new(
                "demoWhich",
                demoWhich,
                options=list(
                    "blank",
                    "d1",
                    "d2",
                    "d3",
                    "d4",
                    "d5",
                    "d6",
                    "d7",
                    "d8",
                    "d9",
                    "d10"),
                default="blank")
            private$..showHTML <- jmvcore::OptionBool$new(
                "showHTML",
                showHTML,
                default=FALSE)
            private$..doProject1sBtn <- jmvcore::OptionAction$new(
                "doProject1sBtn",
                doProject1sBtn)
            private$..doProject1aBtn <- jmvcore::OptionAction$new(
                "doProject1aBtn",
                doProject1aBtn)
            private$..doProject1bBtn <- jmvcore::OptionAction$new(
                "doProject1bBtn",
                doProject1bBtn)
            private$..doProject1cLst <- jmvcore::OptionList$new(
                "doProject1cLst",
                doProject1cLst,
                options=list(
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "StudySubject",
                    "BirthOrder"),
                default="Perfectionism")
            private$..doProject1cLstA <- jmvcore::OptionList$new(
                "doProject1cLstA",
                doProject1cLstA,
                options=list(
                    "ExamGrade",
                    "ExamPass"),
                default="ExamGrade")
            private$..doProject1cBtn <- jmvcore::OptionAction$new(
                "doProject1cBtn",
                doProject1cBtn)
            private$..doProject2aBtn <- jmvcore::OptionAction$new(
                "doProject2aBtn",
                doProject2aBtn)
            private$..doProject2bBtn <- jmvcore::OptionAction$new(
                "doProject2bBtn",
                doProject2bBtn)
            private$..doProject2cBtn <- jmvcore::OptionAction$new(
                "doProject2cBtn",
                doProject2cBtn)
            private$..doProject2dBtn <- jmvcore::OptionAction$new(
                "doProject2dBtn",
                doProject2dBtn)
            private$..doProject3aBtn <- jmvcore::OptionAction$new(
                "doProject3aBtn",
                doProject3aBtn)
            private$..doProject3bBtn <- jmvcore::OptionAction$new(
                "doProject3bBtn",
                doProject3bBtn)
            private$..doProject3cBtn <- jmvcore::OptionAction$new(
                "doProject3cBtn",
                doProject3cBtn)
            private$..doProject3dBtn <- jmvcore::OptionAction$new(
                "doProject3dBtn",
                doProject3dBtn)
            private$..doProject4aBtn <- jmvcore::OptionAction$new(
                "doProject4aBtn",
                doProject4aBtn)
            private$..doProject4bBtn <- jmvcore::OptionAction$new(
                "doProject4bBtn",
                doProject4bBtn)
            private$..doProject4cBtn <- jmvcore::OptionAction$new(
                "doProject4cBtn",
                doProject4cBtn)
            private$..doProject4dBtn <- jmvcore::OptionAction$new(
                "doProject4dBtn",
                doProject4dBtn)
            private$..doProject5sBtn <- jmvcore::OptionAction$new(
                "doProject5sBtn",
                doProject5sBtn)
            private$..doProject5aBtn <- jmvcore::OptionAction$new(
                "doProject5aBtn",
                doProject5aBtn)
            private$..doProject5bBtn <- jmvcore::OptionAction$new(
                "doProject5bBtn",
                doProject5bBtn)
            private$..doProject5cBtn <- jmvcore::OptionAction$new(
                "doProject5cBtn",
                doProject5cBtn)
            private$..doProject5dBtn <- jmvcore::OptionAction$new(
                "doProject5dBtn",
                doProject5dBtn)
            private$..doproject6sBtn <- jmvcore::OptionAction$new(
                "doproject6sBtn",
                doproject6sBtn)
            private$..doproject6aBtn <- jmvcore::OptionAction$new(
                "doproject6aBtn",
                doproject6aBtn)
            private$..doproject6bBtn <- jmvcore::OptionAction$new(
                "doproject6bBtn",
                doproject6bBtn)
            private$..doproject6bLst <- jmvcore::OptionList$new(
                "doproject6bLst",
                doproject6bLst,
                options=list(
                    "n21",
                    "n42",
                    "n84",
                    "n168",
                    "n336"),
                default="n42")
            private$..doproject6cBtn <- jmvcore::OptionAction$new(
                "doproject6cBtn",
                doproject6cBtn)
            private$..doproject6dBtn <- jmvcore::OptionAction$new(
                "doproject6dBtn",
                doproject6dBtn)
            private$..doproject6dLst <- jmvcore::OptionList$new(
                "doproject6dLst",
                doproject6dLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject7sBtn <- jmvcore::OptionAction$new(
                "doproject7sBtn",
                doproject7sBtn)
            private$..doproject7sLst <- jmvcore::OptionList$new(
                "doproject7sLst",
                doproject7sLst,
                options=list(
                    "iii",
                    "ici",
                    "iic",
                    "icc"),
                default="iii")
            private$..doproject7aBtn <- jmvcore::OptionAction$new(
                "doproject7aBtn",
                doproject7aBtn)
            private$..doproject7aLst <- jmvcore::OptionList$new(
                "doproject7aLst",
                doproject7aLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject7bBtn <- jmvcore::OptionAction$new(
                "doproject7bBtn",
                doproject7bBtn)
            private$..doproject7bLst <- jmvcore::OptionList$new(
                "doproject7bLst",
                doproject7bLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject7cBtn <- jmvcore::OptionAction$new(
                "doproject7cBtn",
                doproject7cBtn)
            private$..doproject7cLst <- jmvcore::OptionList$new(
                "doproject7cLst",
                doproject7cLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject7dBtn <- jmvcore::OptionAction$new(
                "doproject7dBtn",
                doproject7dBtn)
            private$..doproject8aBtn <- jmvcore::OptionAction$new(
                "doproject8aBtn",
                doproject8aBtn)
            private$..doproject8aLst <- jmvcore::OptionList$new(
                "doproject8aLst",
                doproject8aLst,
                options=list(
                    "iii",
                    "ici",
                    "iic",
                    "icc"),
                default="iii")
            private$..doproject8bBtn <- jmvcore::OptionAction$new(
                "doproject8bBtn",
                doproject8bBtn)
            private$..doproject8bLst <- jmvcore::OptionList$new(
                "doproject8bLst",
                doproject8bLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject8cBtn <- jmvcore::OptionAction$new(
                "doproject8cBtn",
                doproject8cBtn)
            private$..doproject8cLst <- jmvcore::OptionList$new(
                "doproject8cLst",
                doproject8cLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doProject9sBtn <- jmvcore::OptionAction$new(
                "doProject9sBtn",
                doProject9sBtn)
            private$..doproject9aBtn <- jmvcore::OptionAction$new(
                "doproject9aBtn",
                doproject9aBtn)
            private$..doproject9bBtn <- jmvcore::OptionAction$new(
                "doproject9bBtn",
                doproject9bBtn)
            private$..doproject9bLst <- jmvcore::OptionList$new(
                "doproject9bLst",
                doproject9bLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject9cBtn <- jmvcore::OptionAction$new(
                "doproject9cBtn",
                doproject9cBtn)
            private$..doProject10sBtn <- jmvcore::OptionAction$new(
                "doProject10sBtn",
                doProject10sBtn)
            private$..doproject10aBtn <- jmvcore::OptionAction$new(
                "doproject10aBtn",
                doproject10aBtn)
            private$..doproject10bBtn <- jmvcore::OptionAction$new(
                "doproject10bBtn",
                doproject10bBtn)
            private$..doproject10bLst <- jmvcore::OptionList$new(
                "doproject10bLst",
                doproject10bLst,
                options=list(
                    "r00",
                    "r01",
                    "r02",
                    "r03",
                    "r05",
                    "r075"),
                default="r03")
            private$..doproject10cBtn <- jmvcore::OptionAction$new(
                "doproject10cBtn",
                doproject10cBtn)

            self$.addOption(private$..planOptions)
            self$.addOption(private$..presetDV)
            self$.addOption(private$..presetIV)
            self$.addOption(private$..presetIV2)
            self$.addOption(private$..presetWorld)
            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..DVnlevs)
            self$.addOption(private$..DViqr)
            self$.addOption(private$..DVncats)
            self$.addOption(private$..DVcases)
            self$.addOption(private$..DVprops)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IVnlevs)
            self$.addOption(private$..IViqr)
            self$.addOption(private$..IVncats)
            self$.addOption(private$..IVcases)
            self$.addOption(private$..IVprops)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..IV2nlevs)
            self$.addOption(private$..IV2iqr)
            self$.addOption(private$..IV2ncats)
            self$.addOption(private$..IV2cases)
            self$.addOption(private$..IV2props)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..EffectConfig)
            self$.addOption(private$..Heteroscedasticity)
            self$.addOption(private$..Residuals)
            self$.addOption(private$..WorldOn)
            self$.addOption(private$..WorldPDF)
            self$.addOption(private$..WorldRZ)
            self$.addOption(private$..WorldLambda)
            self$.addOption(private$..WorldNullP)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleSizeM)
            self$.addOption(private$..SampleSpreadOn)
            self$.addOption(private$..SampleGamma)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..SampleUsage1)
            self$.addOption(private$..SampleUsage2)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..NonResponse)
            self$.addOption(private$..LimitRange)
            self$.addOption(private$..RangeMin)
            self$.addOption(private$..RangeMax)
            self$.addOption(private$..Cheating)
            self$.addOption(private$..CheatingAttempts)
            self$.addOption(private$..ReplicationOn)
            self$.addOption(private$..ReplicationPower)
            self$.addOption(private$..ReplicationPrior)
            self$.addOption(private$..ReplicationAttempts)
            self$.addOption(private$..ReplicationDecision)
            self$.addOption(private$..ReplicationAlpha)
            self$.addOption(private$..ReplicationSign)
            self$.addOption(private$..ReplicationSigOriginal)
            self$.addOption(private$..alphaSig)
            self$.addOption(private$..ssq)
            self$.addOption(private$..interaction)
            self$.addOption(private$..equalVar)
            self$.addOption(private$..Transform)
            self$.addOption(private$..likelihoodType)
            self$.addOption(private$..likelihoodCutaway)
            self$.addOption(private$..likelihoodUsePrior)
            self$.addOption(private$..priorPDF)
            self$.addOption(private$..priorRZ)
            self$.addOption(private$..priorLambda)
            self$.addOption(private$..priorNullP)
            self$.addOption(private$..MetaAnalysisOn)
            self$.addOption(private$..MetaAnalysisType)
            self$.addOption(private$..MetaAnalysisNulls)
            self$.addOption(private$..MetaAnalysisBias)
            self$.addOption(private$..MetaAnalysisNStudies)
            self$.addOption(private$..MetaAnalysisStudiesSig)
            self$.addOption(private$..showHypothesisBtn)
            self$.addOption(private$..makeSampleBtn)
            self$.addOption(private$..numberSamples)
            self$.addOption(private$..makeMultipleBtn)
            self$.addOption(private$..inferVar1)
            self$.addOption(private$..inferVar2)
            self$.addOption(private$..showSampleType)
            self$.addOption(private$..showInferDimension)
            self$.addOption(private$..reportInferStats)
            self$.addOption(private$..showMultipleParam)
            self$.addOption(private$..showMultipleDimension)
            self$.addOption(private$..exploreNPointsH)
            self$.addOption(private$..exploreNPointsD)
            self$.addOption(private$..exploreNPointsA)
            self$.addOption(private$..exploreNPointsM)
            self$.addOption(private$..exploreMinValH)
            self$.addOption(private$..exploreMaxValH)
            self$.addOption(private$..exploreMinValD)
            self$.addOption(private$..exploreMaxValD)
            self$.addOption(private$..exploreMinValA)
            self$.addOption(private$..exploreMaxValM)
            self$.addOption(private$..exploreMinValM)
            self$.addOption(private$..exploreMaxValA)
            self$.addOption(private$..exploreXLogH)
            self$.addOption(private$..exploreXLogD)
            self$.addOption(private$..exploreXLogA)
            self$.addOption(private$..exploreXLogM)
            self$.addOption(private$..numberExplores)
            self$.addOption(private$..makeExploreBtn)
            self$.addOption(private$..exploreMode)
            self$.addOption(private$..hypothesisExploreList)
            self$.addOption(private$..designExploreList)
            self$.addOption(private$..analysisExploreList)
            self$.addOption(private$..moreExploreList)
            self$.addOption(private$..showExploreParam)
            self$.addOption(private$..showExploreDimension)
            self$.addOption(private$..whichShowMultiple)
            self$.addOption(private$..sendSample)
            self$.addOption(private$..sendMultiple)
            self$.addOption(private$..jamoviHelp)
            self$.addOption(private$..brawHelp)
            self$.addOption(private$..demoHelp)
            self$.addOption(private$..demoWhich)
            self$.addOption(private$..showHTML)
            self$.addOption(private$..doProject1sBtn)
            self$.addOption(private$..doProject1aBtn)
            self$.addOption(private$..doProject1bBtn)
            self$.addOption(private$..doProject1cLst)
            self$.addOption(private$..doProject1cLstA)
            self$.addOption(private$..doProject1cBtn)
            self$.addOption(private$..doProject2aBtn)
            self$.addOption(private$..doProject2bBtn)
            self$.addOption(private$..doProject2cBtn)
            self$.addOption(private$..doProject2dBtn)
            self$.addOption(private$..doProject3aBtn)
            self$.addOption(private$..doProject3bBtn)
            self$.addOption(private$..doProject3cBtn)
            self$.addOption(private$..doProject3dBtn)
            self$.addOption(private$..doProject4aBtn)
            self$.addOption(private$..doProject4bBtn)
            self$.addOption(private$..doProject4cBtn)
            self$.addOption(private$..doProject4dBtn)
            self$.addOption(private$..doProject5sBtn)
            self$.addOption(private$..doProject5aBtn)
            self$.addOption(private$..doProject5bBtn)
            self$.addOption(private$..doProject5cBtn)
            self$.addOption(private$..doProject5dBtn)
            self$.addOption(private$..doproject6sBtn)
            self$.addOption(private$..doproject6aBtn)
            self$.addOption(private$..doproject6bBtn)
            self$.addOption(private$..doproject6bLst)
            self$.addOption(private$..doproject6cBtn)
            self$.addOption(private$..doproject6dBtn)
            self$.addOption(private$..doproject6dLst)
            self$.addOption(private$..doproject7sBtn)
            self$.addOption(private$..doproject7sLst)
            self$.addOption(private$..doproject7aBtn)
            self$.addOption(private$..doproject7aLst)
            self$.addOption(private$..doproject7bBtn)
            self$.addOption(private$..doproject7bLst)
            self$.addOption(private$..doproject7cBtn)
            self$.addOption(private$..doproject7cLst)
            self$.addOption(private$..doproject7dBtn)
            self$.addOption(private$..doproject8aBtn)
            self$.addOption(private$..doproject8aLst)
            self$.addOption(private$..doproject8bBtn)
            self$.addOption(private$..doproject8bLst)
            self$.addOption(private$..doproject8cBtn)
            self$.addOption(private$..doproject8cLst)
            self$.addOption(private$..doProject9sBtn)
            self$.addOption(private$..doproject9aBtn)
            self$.addOption(private$..doproject9bBtn)
            self$.addOption(private$..doproject9bLst)
            self$.addOption(private$..doproject9cBtn)
            self$.addOption(private$..doProject10sBtn)
            self$.addOption(private$..doproject10aBtn)
            self$.addOption(private$..doproject10bBtn)
            self$.addOption(private$..doproject10bLst)
            self$.addOption(private$..doproject10cBtn)
        }),
    active = list(
        planOptions = function() private$..planOptions$value,
        presetDV = function() private$..presetDV$value,
        presetIV = function() private$..presetIV$value,
        presetIV2 = function() private$..presetIV2$value,
        presetWorld = function() private$..presetWorld$value,
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        DVnlevs = function() private$..DVnlevs$value,
        DViqr = function() private$..DViqr$value,
        DVncats = function() private$..DVncats$value,
        DVcases = function() private$..DVcases$value,
        DVprops = function() private$..DVprops$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IVnlevs = function() private$..IVnlevs$value,
        IViqr = function() private$..IViqr$value,
        IVncats = function() private$..IVncats$value,
        IVcases = function() private$..IVcases$value,
        IVprops = function() private$..IVprops$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        IV2nlevs = function() private$..IV2nlevs$value,
        IV2iqr = function() private$..IV2iqr$value,
        IV2ncats = function() private$..IV2ncats$value,
        IV2cases = function() private$..IV2cases$value,
        IV2props = function() private$..IV2props$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        EffectConfig = function() private$..EffectConfig$value,
        Heteroscedasticity = function() private$..Heteroscedasticity$value,
        Residuals = function() private$..Residuals$value,
        WorldOn = function() private$..WorldOn$value,
        WorldPDF = function() private$..WorldPDF$value,
        WorldRZ = function() private$..WorldRZ$value,
        WorldLambda = function() private$..WorldLambda$value,
        WorldNullP = function() private$..WorldNullP$value,
        SampleSize = function() private$..SampleSize$value,
        SampleSizeM = function() private$..SampleSizeM$value,
        SampleSpreadOn = function() private$..SampleSpreadOn$value,
        SampleGamma = function() private$..SampleGamma$value,
        SampleMethod = function() private$..SampleMethod$value,
        SampleUsage1 = function() private$..SampleUsage1$value,
        SampleUsage2 = function() private$..SampleUsage2$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        NonResponse = function() private$..NonResponse$value,
        LimitRange = function() private$..LimitRange$value,
        RangeMin = function() private$..RangeMin$value,
        RangeMax = function() private$..RangeMax$value,
        Cheating = function() private$..Cheating$value,
        CheatingAttempts = function() private$..CheatingAttempts$value,
        ReplicationOn = function() private$..ReplicationOn$value,
        ReplicationPower = function() private$..ReplicationPower$value,
        ReplicationPrior = function() private$..ReplicationPrior$value,
        ReplicationAttempts = function() private$..ReplicationAttempts$value,
        ReplicationDecision = function() private$..ReplicationDecision$value,
        ReplicationAlpha = function() private$..ReplicationAlpha$value,
        ReplicationSign = function() private$..ReplicationSign$value,
        ReplicationSigOriginal = function() private$..ReplicationSigOriginal$value,
        alphaSig = function() private$..alphaSig$value,
        ssq = function() private$..ssq$value,
        interaction = function() private$..interaction$value,
        equalVar = function() private$..equalVar$value,
        Transform = function() private$..Transform$value,
        likelihoodType = function() private$..likelihoodType$value,
        likelihoodCutaway = function() private$..likelihoodCutaway$value,
        likelihoodUsePrior = function() private$..likelihoodUsePrior$value,
        priorPDF = function() private$..priorPDF$value,
        priorRZ = function() private$..priorRZ$value,
        priorLambda = function() private$..priorLambda$value,
        priorNullP = function() private$..priorNullP$value,
        MetaAnalysisOn = function() private$..MetaAnalysisOn$value,
        MetaAnalysisType = function() private$..MetaAnalysisType$value,
        MetaAnalysisNulls = function() private$..MetaAnalysisNulls$value,
        MetaAnalysisBias = function() private$..MetaAnalysisBias$value,
        MetaAnalysisNStudies = function() private$..MetaAnalysisNStudies$value,
        MetaAnalysisStudiesSig = function() private$..MetaAnalysisStudiesSig$value,
        showHypothesisBtn = function() private$..showHypothesisBtn$value,
        makeSampleBtn = function() private$..makeSampleBtn$value,
        numberSamples = function() private$..numberSamples$value,
        makeMultipleBtn = function() private$..makeMultipleBtn$value,
        inferVar1 = function() private$..inferVar1$value,
        inferVar2 = function() private$..inferVar2$value,
        showSampleType = function() private$..showSampleType$value,
        showInferDimension = function() private$..showInferDimension$value,
        reportInferStats = function() private$..reportInferStats$value,
        showMultipleParam = function() private$..showMultipleParam$value,
        showMultipleDimension = function() private$..showMultipleDimension$value,
        exploreNPointsH = function() private$..exploreNPointsH$value,
        exploreNPointsD = function() private$..exploreNPointsD$value,
        exploreNPointsA = function() private$..exploreNPointsA$value,
        exploreNPointsM = function() private$..exploreNPointsM$value,
        exploreMinValH = function() private$..exploreMinValH$value,
        exploreMaxValH = function() private$..exploreMaxValH$value,
        exploreMinValD = function() private$..exploreMinValD$value,
        exploreMaxValD = function() private$..exploreMaxValD$value,
        exploreMinValA = function() private$..exploreMinValA$value,
        exploreMaxValM = function() private$..exploreMaxValM$value,
        exploreMinValM = function() private$..exploreMinValM$value,
        exploreMaxValA = function() private$..exploreMaxValA$value,
        exploreXLogH = function() private$..exploreXLogH$value,
        exploreXLogD = function() private$..exploreXLogD$value,
        exploreXLogA = function() private$..exploreXLogA$value,
        exploreXLogM = function() private$..exploreXLogM$value,
        numberExplores = function() private$..numberExplores$value,
        makeExploreBtn = function() private$..makeExploreBtn$value,
        exploreMode = function() private$..exploreMode$value,
        hypothesisExploreList = function() private$..hypothesisExploreList$value,
        designExploreList = function() private$..designExploreList$value,
        analysisExploreList = function() private$..analysisExploreList$value,
        moreExploreList = function() private$..moreExploreList$value,
        showExploreParam = function() private$..showExploreParam$value,
        showExploreDimension = function() private$..showExploreDimension$value,
        whichShowMultiple = function() private$..whichShowMultiple$value,
        sendSample = function() private$..sendSample$value,
        sendMultiple = function() private$..sendMultiple$value,
        jamoviHelp = function() private$..jamoviHelp$value,
        brawHelp = function() private$..brawHelp$value,
        demoHelp = function() private$..demoHelp$value,
        demoWhich = function() private$..demoWhich$value,
        showHTML = function() private$..showHTML$value,
        doProject1sBtn = function() private$..doProject1sBtn$value,
        doProject1aBtn = function() private$..doProject1aBtn$value,
        doProject1bBtn = function() private$..doProject1bBtn$value,
        doProject1cLst = function() private$..doProject1cLst$value,
        doProject1cLstA = function() private$..doProject1cLstA$value,
        doProject1cBtn = function() private$..doProject1cBtn$value,
        doProject2aBtn = function() private$..doProject2aBtn$value,
        doProject2bBtn = function() private$..doProject2bBtn$value,
        doProject2cBtn = function() private$..doProject2cBtn$value,
        doProject2dBtn = function() private$..doProject2dBtn$value,
        doProject3aBtn = function() private$..doProject3aBtn$value,
        doProject3bBtn = function() private$..doProject3bBtn$value,
        doProject3cBtn = function() private$..doProject3cBtn$value,
        doProject3dBtn = function() private$..doProject3dBtn$value,
        doProject4aBtn = function() private$..doProject4aBtn$value,
        doProject4bBtn = function() private$..doProject4bBtn$value,
        doProject4cBtn = function() private$..doProject4cBtn$value,
        doProject4dBtn = function() private$..doProject4dBtn$value,
        doProject5sBtn = function() private$..doProject5sBtn$value,
        doProject5aBtn = function() private$..doProject5aBtn$value,
        doProject5bBtn = function() private$..doProject5bBtn$value,
        doProject5cBtn = function() private$..doProject5cBtn$value,
        doProject5dBtn = function() private$..doProject5dBtn$value,
        doproject6sBtn = function() private$..doproject6sBtn$value,
        doproject6aBtn = function() private$..doproject6aBtn$value,
        doproject6bBtn = function() private$..doproject6bBtn$value,
        doproject6bLst = function() private$..doproject6bLst$value,
        doproject6cBtn = function() private$..doproject6cBtn$value,
        doproject6dBtn = function() private$..doproject6dBtn$value,
        doproject6dLst = function() private$..doproject6dLst$value,
        doproject7sBtn = function() private$..doproject7sBtn$value,
        doproject7sLst = function() private$..doproject7sLst$value,
        doproject7aBtn = function() private$..doproject7aBtn$value,
        doproject7aLst = function() private$..doproject7aLst$value,
        doproject7bBtn = function() private$..doproject7bBtn$value,
        doproject7bLst = function() private$..doproject7bLst$value,
        doproject7cBtn = function() private$..doproject7cBtn$value,
        doproject7cLst = function() private$..doproject7cLst$value,
        doproject7dBtn = function() private$..doproject7dBtn$value,
        doproject8aBtn = function() private$..doproject8aBtn$value,
        doproject8aLst = function() private$..doproject8aLst$value,
        doproject8bBtn = function() private$..doproject8bBtn$value,
        doproject8bLst = function() private$..doproject8bLst$value,
        doproject8cBtn = function() private$..doproject8cBtn$value,
        doproject8cLst = function() private$..doproject8cLst$value,
        doProject9sBtn = function() private$..doProject9sBtn$value,
        doproject9aBtn = function() private$..doproject9aBtn$value,
        doproject9bBtn = function() private$..doproject9bBtn$value,
        doproject9bLst = function() private$..doproject9bLst$value,
        doproject9cBtn = function() private$..doproject9cBtn$value,
        doProject10sBtn = function() private$..doProject10sBtn$value,
        doproject10aBtn = function() private$..doproject10aBtn$value,
        doproject10bBtn = function() private$..doproject10bBtn$value,
        doproject10bLst = function() private$..doproject10bLst$value,
        doproject10cBtn = function() private$..doproject10cBtn$value),
    private = list(
        ..planOptions = NA,
        ..presetDV = NA,
        ..presetIV = NA,
        ..presetIV2 = NA,
        ..presetWorld = NA,
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..DVnlevs = NA,
        ..DViqr = NA,
        ..DVncats = NA,
        ..DVcases = NA,
        ..DVprops = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IVnlevs = NA,
        ..IViqr = NA,
        ..IVncats = NA,
        ..IVcases = NA,
        ..IVprops = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..IV2nlevs = NA,
        ..IV2iqr = NA,
        ..IV2ncats = NA,
        ..IV2cases = NA,
        ..IV2props = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..EffectConfig = NA,
        ..Heteroscedasticity = NA,
        ..Residuals = NA,
        ..WorldOn = NA,
        ..WorldPDF = NA,
        ..WorldRZ = NA,
        ..WorldLambda = NA,
        ..WorldNullP = NA,
        ..SampleSize = NA,
        ..SampleSizeM = NA,
        ..SampleSpreadOn = NA,
        ..SampleGamma = NA,
        ..SampleMethod = NA,
        ..SampleUsage1 = NA,
        ..SampleUsage2 = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..NonResponse = NA,
        ..LimitRange = NA,
        ..RangeMin = NA,
        ..RangeMax = NA,
        ..Cheating = NA,
        ..CheatingAttempts = NA,
        ..ReplicationOn = NA,
        ..ReplicationPower = NA,
        ..ReplicationPrior = NA,
        ..ReplicationAttempts = NA,
        ..ReplicationDecision = NA,
        ..ReplicationAlpha = NA,
        ..ReplicationSign = NA,
        ..ReplicationSigOriginal = NA,
        ..alphaSig = NA,
        ..ssq = NA,
        ..interaction = NA,
        ..equalVar = NA,
        ..Transform = NA,
        ..likelihoodType = NA,
        ..likelihoodCutaway = NA,
        ..likelihoodUsePrior = NA,
        ..priorPDF = NA,
        ..priorRZ = NA,
        ..priorLambda = NA,
        ..priorNullP = NA,
        ..MetaAnalysisOn = NA,
        ..MetaAnalysisType = NA,
        ..MetaAnalysisNulls = NA,
        ..MetaAnalysisBias = NA,
        ..MetaAnalysisNStudies = NA,
        ..MetaAnalysisStudiesSig = NA,
        ..showHypothesisBtn = NA,
        ..makeSampleBtn = NA,
        ..numberSamples = NA,
        ..makeMultipleBtn = NA,
        ..inferVar1 = NA,
        ..inferVar2 = NA,
        ..showSampleType = NA,
        ..showInferDimension = NA,
        ..reportInferStats = NA,
        ..showMultipleParam = NA,
        ..showMultipleDimension = NA,
        ..exploreNPointsH = NA,
        ..exploreNPointsD = NA,
        ..exploreNPointsA = NA,
        ..exploreNPointsM = NA,
        ..exploreMinValH = NA,
        ..exploreMaxValH = NA,
        ..exploreMinValD = NA,
        ..exploreMaxValD = NA,
        ..exploreMinValA = NA,
        ..exploreMaxValM = NA,
        ..exploreMinValM = NA,
        ..exploreMaxValA = NA,
        ..exploreXLogH = NA,
        ..exploreXLogD = NA,
        ..exploreXLogA = NA,
        ..exploreXLogM = NA,
        ..numberExplores = NA,
        ..makeExploreBtn = NA,
        ..exploreMode = NA,
        ..hypothesisExploreList = NA,
        ..designExploreList = NA,
        ..analysisExploreList = NA,
        ..moreExploreList = NA,
        ..showExploreParam = NA,
        ..showExploreDimension = NA,
        ..whichShowMultiple = NA,
        ..sendSample = NA,
        ..sendMultiple = NA,
        ..jamoviHelp = NA,
        ..brawHelp = NA,
        ..demoHelp = NA,
        ..demoWhich = NA,
        ..showHTML = NA,
        ..doProject1sBtn = NA,
        ..doProject1aBtn = NA,
        ..doProject1bBtn = NA,
        ..doProject1cLst = NA,
        ..doProject1cLstA = NA,
        ..doProject1cBtn = NA,
        ..doProject2aBtn = NA,
        ..doProject2bBtn = NA,
        ..doProject2cBtn = NA,
        ..doProject2dBtn = NA,
        ..doProject3aBtn = NA,
        ..doProject3bBtn = NA,
        ..doProject3cBtn = NA,
        ..doProject3dBtn = NA,
        ..doProject4aBtn = NA,
        ..doProject4bBtn = NA,
        ..doProject4cBtn = NA,
        ..doProject4dBtn = NA,
        ..doProject5sBtn = NA,
        ..doProject5aBtn = NA,
        ..doProject5bBtn = NA,
        ..doProject5cBtn = NA,
        ..doProject5dBtn = NA,
        ..doproject6sBtn = NA,
        ..doproject6aBtn = NA,
        ..doproject6bBtn = NA,
        ..doproject6bLst = NA,
        ..doproject6cBtn = NA,
        ..doproject6dBtn = NA,
        ..doproject6dLst = NA,
        ..doproject7sBtn = NA,
        ..doproject7sLst = NA,
        ..doproject7aBtn = NA,
        ..doproject7aLst = NA,
        ..doproject7bBtn = NA,
        ..doproject7bLst = NA,
        ..doproject7cBtn = NA,
        ..doproject7cLst = NA,
        ..doproject7dBtn = NA,
        ..doproject8aBtn = NA,
        ..doproject8aLst = NA,
        ..doproject8bBtn = NA,
        ..doproject8bLst = NA,
        ..doproject8cBtn = NA,
        ..doproject8cLst = NA,
        ..doProject9sBtn = NA,
        ..doproject9aBtn = NA,
        ..doproject9bBtn = NA,
        ..doproject9bLst = NA,
        ..doproject9cBtn = NA,
        ..doProject10sBtn = NA,
        ..doproject10aBtn = NA,
        ..doproject10bBtn = NA,
        ..doproject10bLst = NA,
        ..doproject10cBtn = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        BrawStatsInstructions = function() private$.items[["BrawStatsInstructions"]],
        simGraphHTML = function() private$.items[["simGraphHTML"]],
        simGraph = function() private$.items[["simGraph"]],
        simReport = function() private$.items[["simReport"]],
        debug = function() private$.items[["debug"]],
        sendSample = function() private$.items[["sendSample"]],
        sendMultiple = function() private$.items[["sendMultiple"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Simulate Data",
                refs="brawstats book")
            self$add(jmvcore::Html$new(
                options=options,
                name="BrawStatsInstructions",
                visible=TRUE,
                clearWith=list(
                    "jamoviHelp")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simGraphHTML",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="simGraph",
                title=" ",
                width=550,
                height=400,
                visible=TRUE,
                renderFun=".plotSimGraph",
                clearWith=list(
                    "showHypothesisBtn",
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "singleVar1",
                    "singleVar2",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "multipleVar1",
                    "multipleVar2",
                    "showMultipleDimension",
                    "makeExploreBtn",
                    "showExploreParam",
                    "exploreVar1",
                    "exploreVar2",
                    "showExploreDimension",
                    "whichShowMultiple")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simReport",
                title=" ",
                visible=TRUE,
                clearWith=list(
                    "showHypothesisBtn",
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "singleVar1",
                    "singleVar2",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "multipleVar1",
                    "multipleVar2",
                    "showMultipleDimension",
                    "reportMultipleStats",
                    "makeExploreBtn",
                    "showExploreParam",
                    "exploreVar1",
                    "exploreVar2",
                    "showExploreDimension",
                    "reportExploreStats",
                    "whichShowMultiple"),
                refs=list(
                    "brawstats",
                    "book")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSample",
                measureType="nominal",
                varTitle="Sample",
                items=4,
                clearWith=list(
                    "makeSampleBtn")))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendMultiple",
                measureType="continuous",
                varTitle="Mult",
                items=3,
                clearWith=list(
                    "makeMultipleBtn")))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' BrawStats:Simulate Data
#'
#' 
#' @param planOptions .
#' @param presetDV .
#' @param presetIV .
#' @param presetIV2 .
#' @param presetWorld .
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param DVnlevs .
#' @param DViqr .
#' @param DVncats .
#' @param DVcases .
#' @param DVprops .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IVnlevs .
#' @param IViqr .
#' @param IVncats .
#' @param IVcases .
#' @param IVprops .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param IV2nlevs .
#' @param IV2iqr .
#' @param IV2ncats .
#' @param IV2cases .
#' @param IV2props .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param EffectConfig .
#' @param Heteroscedasticity .
#' @param Residuals .
#' @param WorldOn .
#' @param WorldPDF .
#' @param WorldRZ .
#' @param WorldLambda .
#' @param WorldNullP .
#' @param SampleSize .
#' @param SampleSizeM .
#' @param SampleSpreadOn .
#' @param SampleGamma .
#' @param SampleMethod .
#' @param SampleUsage1 .
#' @param SampleUsage2 .
#' @param Dependence .
#' @param Outliers .
#' @param NonResponse .
#' @param LimitRange .
#' @param RangeMin .
#' @param RangeMax .
#' @param Cheating .
#' @param CheatingAttempts .
#' @param ReplicationOn .
#' @param ReplicationPower .
#' @param ReplicationPrior .
#' @param ReplicationAttempts .
#' @param ReplicationDecision .
#' @param ReplicationAlpha .
#' @param ReplicationSign .
#' @param ReplicationSigOriginal .
#' @param alphaSig .
#' @param ssq .
#' @param interaction .
#' @param equalVar .
#' @param Transform .
#' @param likelihoodType .
#' @param likelihoodCutaway .
#' @param likelihoodUsePrior .
#' @param priorPDF .
#' @param priorRZ .
#' @param priorLambda .
#' @param priorNullP .
#' @param MetaAnalysisOn .
#' @param MetaAnalysisType .
#' @param MetaAnalysisNulls .
#' @param MetaAnalysisBias .
#' @param MetaAnalysisNStudies .
#' @param MetaAnalysisStudiesSig .
#' @param showHypothesisBtn .
#' @param makeSampleBtn .
#' @param numberSamples .
#' @param makeMultipleBtn .
#' @param inferVar1 .
#' @param inferVar2 .
#' @param showSampleType .
#' @param showInferDimension .
#' @param reportInferStats .
#' @param showMultipleParam .
#' @param showMultipleDimension .
#' @param exploreNPointsH .
#' @param exploreNPointsD .
#' @param exploreNPointsA .
#' @param exploreNPointsM .
#' @param exploreMinValH .
#' @param exploreMaxValH .
#' @param exploreMinValD .
#' @param exploreMaxValD .
#' @param exploreMinValA .
#' @param exploreMaxValM .
#' @param exploreMinValM .
#' @param exploreMaxValA .
#' @param exploreXLogH .
#' @param exploreXLogD .
#' @param exploreXLogA .
#' @param exploreXLogM .
#' @param numberExplores .
#' @param makeExploreBtn .
#' @param exploreMode .
#' @param hypothesisExploreList .
#' @param designExploreList .
#' @param analysisExploreList .
#' @param moreExploreList .
#' @param showExploreParam .
#' @param showExploreDimension .
#' @param whichShowMultiple .
#' @param jamoviHelp .
#' @param brawHelp .
#' @param demoHelp .
#' @param demoWhich .
#' @param showHTML .
#' @param doProject1sBtn .
#' @param doProject1aBtn .
#' @param doProject1bBtn .
#' @param doProject1cLst .
#' @param doProject1cLstA .
#' @param doProject1cBtn .
#' @param doProject2aBtn .
#' @param doProject2bBtn .
#' @param doProject2cBtn .
#' @param doProject2dBtn .
#' @param doProject3aBtn .
#' @param doProject3bBtn .
#' @param doProject3cBtn .
#' @param doProject3dBtn .
#' @param doProject4aBtn .
#' @param doProject4bBtn .
#' @param doProject4cBtn .
#' @param doProject4dBtn .
#' @param doProject5sBtn .
#' @param doProject5aBtn .
#' @param doProject5bBtn .
#' @param doProject5cBtn .
#' @param doProject5dBtn .
#' @param doproject6sBtn .
#' @param doproject6aBtn .
#' @param doproject6bBtn .
#' @param doproject6bLst .
#' @param doproject6cBtn .
#' @param doproject6dBtn .
#' @param doproject6dLst .
#' @param doproject7sBtn .
#' @param doproject7sLst .
#' @param doproject7aBtn .
#' @param doproject7aLst .
#' @param doproject7bBtn .
#' @param doproject7bLst .
#' @param doproject7cBtn .
#' @param doproject7cLst .
#' @param doproject7dBtn .
#' @param doproject8aBtn .
#' @param doproject8aLst .
#' @param doproject8bBtn .
#' @param doproject8bLst .
#' @param doproject8cBtn .
#' @param doproject8cLst .
#' @param doProject9sBtn .
#' @param doproject9aBtn .
#' @param doproject9bBtn .
#' @param doproject9bLst .
#' @param doproject9cBtn .
#' @param doProject10sBtn .
#' @param doproject10aBtn .
#' @param doproject10bBtn .
#' @param doproject10bLst .
#' @param doproject10cBtn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$BrawStatsInstructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simGraphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sendSample} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendMultiple} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
BrawSim <- function(
    planOptions,
    presetDV = "Blank",
    presetIV = "Blank",
    presetIV2 = "none",
    presetWorld = "simple",
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 0,
    DVnlevs = 7,
    DViqr = 4,
    DVncats = 2,
    DVcases = "C1,C2",
    DVprops = "1,1",
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 0,
    IVnlevs = 7,
    IViqr = 4,
    IVncats = 2,
    IVcases = "C1,C2",
    IVprops = "1,1",
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 0,
    IV2nlevs = 7,
    IV2iqr = 4,
    IV2ncats = 2,
    IV2cases = "C1,C2",
    IV2props = "1,1",
    EffectSize1 = 0,
    EffectSize2 = 0,
    EffectSize3 = 0,
    EffectSize12 = 0,
    EffectConfig = "normal",
    Heteroscedasticity = 0,
    Residuals = "normal",
    WorldOn = FALSE,
    WorldPDF = "Single",
    WorldRZ,
    WorldLambda = 0.3,
    WorldNullP = 0.5,
    SampleSize = 42,
    SampleSizeM = 42,
    SampleSpreadOn = FALSE,
    SampleGamma = 1.56,
    SampleMethod = "Random",
    SampleUsage1 = "Between",
    SampleUsage2 = "Between",
    Dependence = 0,
    Outliers = 0,
    NonResponse = 0,
    LimitRange = "no",
    RangeMin = -3,
    RangeMax = 3,
    Cheating = "None",
    CheatingAttempts = 5,
    ReplicationOn = FALSE,
    ReplicationPower = 0.8,
    ReplicationPrior = "None",
    ReplicationAttempts = 1,
    ReplicationDecision = "Cautious",
    ReplicationAlpha = 0.05,
    ReplicationSign = "yes",
    ReplicationSigOriginal = "yes",
    alphaSig = 0.05,
    ssq = "Type3",
    interaction = "no",
    equalVar = "yes",
    Transform = "None",
    likelihoodType = "Populations",
    likelihoodCutaway = "cutaway",
    likelihoodUsePrior = "none",
    priorPDF = "Exp",
    priorRZ = "z",
    priorLambda = 0.3,
    priorNullP = 0,
    MetaAnalysisOn = FALSE,
    MetaAnalysisType = "random",
    MetaAnalysisNulls = "yes",
    MetaAnalysisBias = "yes",
    MetaAnalysisNStudies = 10,
    MetaAnalysisStudiesSig = "sigOnly",
    showHypothesisBtn,
    makeSampleBtn = FALSE,
    numberSamples = 100,
    makeMultipleBtn,
    inferVar1 = "rs",
    inferVar2 = "p",
    showSampleType = "Compact",
    showInferDimension = "1D",
    reportInferStats = "Medians",
    showMultipleParam = "Basic",
    showMultipleDimension = "1D",
    exploreNPointsH = 13,
    exploreNPointsD = 13,
    exploreNPointsA = 13,
    exploreNPointsM = 13,
    exploreMinValH = "-0.9",
    exploreMaxValH = "0.9",
    exploreMinValD = "10",
    exploreMaxValD = "250",
    exploreMinValA = "0.001",
    exploreMaxValM = "0.5",
    exploreMinValM = "0.001",
    exploreMaxValA = "0.5",
    exploreXLogH = FALSE,
    exploreXLogD = FALSE,
    exploreXLogA = FALSE,
    exploreXLogM = FALSE,
    numberExplores = 10,
    makeExploreBtn,
    exploreMode = "designExplore",
    hypothesisExploreList,
    designExploreList,
    analysisExploreList,
    moreExploreList,
    showExploreParam = "Basic",
    showExploreDimension = "1D",
    whichShowMultiple = "all",
    jamoviHelp = FALSE,
    brawHelp = TRUE,
    demoHelp = TRUE,
    demoWhich = "blank",
    showHTML = FALSE,
    doProject1sBtn,
    doProject1aBtn,
    doProject1bBtn,
    doProject1cLst = "Perfectionism",
    doProject1cLstA = "ExamGrade",
    doProject1cBtn,
    doProject2aBtn,
    doProject2bBtn,
    doProject2cBtn,
    doProject2dBtn,
    doProject3aBtn,
    doProject3bBtn,
    doProject3cBtn,
    doProject3dBtn,
    doProject4aBtn,
    doProject4bBtn,
    doProject4cBtn,
    doProject4dBtn,
    doProject5sBtn,
    doProject5aBtn,
    doProject5bBtn,
    doProject5cBtn,
    doProject5dBtn,
    doproject6sBtn,
    doproject6aBtn,
    doproject6bBtn,
    doproject6bLst = "n42",
    doproject6cBtn,
    doproject6dBtn,
    doproject6dLst = "r03",
    doproject7sBtn,
    doproject7sLst = "iii",
    doproject7aBtn,
    doproject7aLst = "r03",
    doproject7bBtn,
    doproject7bLst = "r03",
    doproject7cBtn,
    doproject7cLst = "r03",
    doproject7dBtn,
    doproject8aBtn,
    doproject8aLst = "iii",
    doproject8bBtn,
    doproject8bLst = "r03",
    doproject8cBtn,
    doproject8cLst = "r03",
    doProject9sBtn,
    doproject9aBtn,
    doproject9bBtn,
    doproject9bLst = "r03",
    doproject9cBtn,
    doProject10sBtn,
    doproject10aBtn,
    doproject10bBtn,
    doproject10bLst = "r03",
    doproject10cBtn) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        planOptions = planOptions,
        presetDV = presetDV,
        presetIV = presetIV,
        presetIV2 = presetIV2,
        presetWorld = presetWorld,
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        DVnlevs = DVnlevs,
        DViqr = DViqr,
        DVncats = DVncats,
        DVcases = DVcases,
        DVprops = DVprops,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IVnlevs = IVnlevs,
        IViqr = IViqr,
        IVncats = IVncats,
        IVcases = IVcases,
        IVprops = IVprops,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        IV2nlevs = IV2nlevs,
        IV2iqr = IV2iqr,
        IV2ncats = IV2ncats,
        IV2cases = IV2cases,
        IV2props = IV2props,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        EffectConfig = EffectConfig,
        Heteroscedasticity = Heteroscedasticity,
        Residuals = Residuals,
        WorldOn = WorldOn,
        WorldPDF = WorldPDF,
        WorldRZ = WorldRZ,
        WorldLambda = WorldLambda,
        WorldNullP = WorldNullP,
        SampleSize = SampleSize,
        SampleSizeM = SampleSizeM,
        SampleSpreadOn = SampleSpreadOn,
        SampleGamma = SampleGamma,
        SampleMethod = SampleMethod,
        SampleUsage1 = SampleUsage1,
        SampleUsage2 = SampleUsage2,
        Dependence = Dependence,
        Outliers = Outliers,
        NonResponse = NonResponse,
        LimitRange = LimitRange,
        RangeMin = RangeMin,
        RangeMax = RangeMax,
        Cheating = Cheating,
        CheatingAttempts = CheatingAttempts,
        ReplicationOn = ReplicationOn,
        ReplicationPower = ReplicationPower,
        ReplicationPrior = ReplicationPrior,
        ReplicationAttempts = ReplicationAttempts,
        ReplicationDecision = ReplicationDecision,
        ReplicationAlpha = ReplicationAlpha,
        ReplicationSign = ReplicationSign,
        ReplicationSigOriginal = ReplicationSigOriginal,
        alphaSig = alphaSig,
        ssq = ssq,
        interaction = interaction,
        equalVar = equalVar,
        Transform = Transform,
        likelihoodType = likelihoodType,
        likelihoodCutaway = likelihoodCutaway,
        likelihoodUsePrior = likelihoodUsePrior,
        priorPDF = priorPDF,
        priorRZ = priorRZ,
        priorLambda = priorLambda,
        priorNullP = priorNullP,
        MetaAnalysisOn = MetaAnalysisOn,
        MetaAnalysisType = MetaAnalysisType,
        MetaAnalysisNulls = MetaAnalysisNulls,
        MetaAnalysisBias = MetaAnalysisBias,
        MetaAnalysisNStudies = MetaAnalysisNStudies,
        MetaAnalysisStudiesSig = MetaAnalysisStudiesSig,
        showHypothesisBtn = showHypothesisBtn,
        makeSampleBtn = makeSampleBtn,
        numberSamples = numberSamples,
        makeMultipleBtn = makeMultipleBtn,
        inferVar1 = inferVar1,
        inferVar2 = inferVar2,
        showSampleType = showSampleType,
        showInferDimension = showInferDimension,
        reportInferStats = reportInferStats,
        showMultipleParam = showMultipleParam,
        showMultipleDimension = showMultipleDimension,
        exploreNPointsH = exploreNPointsH,
        exploreNPointsD = exploreNPointsD,
        exploreNPointsA = exploreNPointsA,
        exploreNPointsM = exploreNPointsM,
        exploreMinValH = exploreMinValH,
        exploreMaxValH = exploreMaxValH,
        exploreMinValD = exploreMinValD,
        exploreMaxValD = exploreMaxValD,
        exploreMinValA = exploreMinValA,
        exploreMaxValM = exploreMaxValM,
        exploreMinValM = exploreMinValM,
        exploreMaxValA = exploreMaxValA,
        exploreXLogH = exploreXLogH,
        exploreXLogD = exploreXLogD,
        exploreXLogA = exploreXLogA,
        exploreXLogM = exploreXLogM,
        numberExplores = numberExplores,
        makeExploreBtn = makeExploreBtn,
        exploreMode = exploreMode,
        hypothesisExploreList = hypothesisExploreList,
        designExploreList = designExploreList,
        analysisExploreList = analysisExploreList,
        moreExploreList = moreExploreList,
        showExploreParam = showExploreParam,
        showExploreDimension = showExploreDimension,
        whichShowMultiple = whichShowMultiple,
        jamoviHelp = jamoviHelp,
        brawHelp = brawHelp,
        demoHelp = demoHelp,
        demoWhich = demoWhich,
        showHTML = showHTML,
        doProject1sBtn = doProject1sBtn,
        doProject1aBtn = doProject1aBtn,
        doProject1bBtn = doProject1bBtn,
        doProject1cLst = doProject1cLst,
        doProject1cLstA = doProject1cLstA,
        doProject1cBtn = doProject1cBtn,
        doProject2aBtn = doProject2aBtn,
        doProject2bBtn = doProject2bBtn,
        doProject2cBtn = doProject2cBtn,
        doProject2dBtn = doProject2dBtn,
        doProject3aBtn = doProject3aBtn,
        doProject3bBtn = doProject3bBtn,
        doProject3cBtn = doProject3cBtn,
        doProject3dBtn = doProject3dBtn,
        doProject4aBtn = doProject4aBtn,
        doProject4bBtn = doProject4bBtn,
        doProject4cBtn = doProject4cBtn,
        doProject4dBtn = doProject4dBtn,
        doProject5sBtn = doProject5sBtn,
        doProject5aBtn = doProject5aBtn,
        doProject5bBtn = doProject5bBtn,
        doProject5cBtn = doProject5cBtn,
        doProject5dBtn = doProject5dBtn,
        doproject6sBtn = doproject6sBtn,
        doproject6aBtn = doproject6aBtn,
        doproject6bBtn = doproject6bBtn,
        doproject6bLst = doproject6bLst,
        doproject6cBtn = doproject6cBtn,
        doproject6dBtn = doproject6dBtn,
        doproject6dLst = doproject6dLst,
        doproject7sBtn = doproject7sBtn,
        doproject7sLst = doproject7sLst,
        doproject7aBtn = doproject7aBtn,
        doproject7aLst = doproject7aLst,
        doproject7bBtn = doproject7bBtn,
        doproject7bLst = doproject7bLst,
        doproject7cBtn = doproject7cBtn,
        doproject7cLst = doproject7cLst,
        doproject7dBtn = doproject7dBtn,
        doproject8aBtn = doproject8aBtn,
        doproject8aLst = doproject8aLst,
        doproject8bBtn = doproject8bBtn,
        doproject8bLst = doproject8bLst,
        doproject8cBtn = doproject8cBtn,
        doproject8cLst = doproject8cLst,
        doProject9sBtn = doProject9sBtn,
        doproject9aBtn = doproject9aBtn,
        doproject9bBtn = doproject9bBtn,
        doproject9bLst = doproject9bLst,
        doproject9cBtn = doproject9cBtn,
        doProject10sBtn = doProject10sBtn,
        doproject10aBtn = doproject10aBtn,
        doproject10bBtn = doproject10bBtn,
        doproject10bLst = doproject10bLst,
        doproject10cBtn = doproject10cBtn)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

