
# This file is automatically generated, you probably don't want to edit this

BrawAnOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL,
            alphaSig = 0.05,
            ssq = "Type3",
            interaction = "no",
            equalVar = "yes",
            Transform = "None",
            show = "Compact",
            inferWhich = "2D", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawAn",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariables$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..alphaSig <- jmvcore::OptionNumber$new(
                "alphaSig",
                alphaSig,
                default=0.05)
            private$..ssq <- jmvcore::OptionList$new(
                "ssq",
                ssq,
                options=list(
                    "Type1",
                    "Type2",
                    "Type3"),
                default="Type3")
            private$..interaction <- jmvcore::OptionList$new(
                "interaction",
                interaction,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..equalVar <- jmvcore::OptionList$new(
                "equalVar",
                equalVar,
                options=list(
                    "no",
                    "yes"),
                default="yes")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..show <- jmvcore::OptionList$new(
                "show",
                show,
                options=list(
                    "Compact",
                    "Sample",
                    "Describe",
                    "Infer",
                    "Likelihood"),
                default="Compact")
            private$..inferWhich <- jmvcore::OptionList$new(
                "inferWhich",
                inferWhich,
                options=list(
                    "r",
                    "p",
                    "2D"),
                default="2D")

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..alphaSig)
            self$.addOption(private$..ssq)
            self$.addOption(private$..interaction)
            self$.addOption(private$..equalVar)
            self$.addOption(private$..Transform)
            self$.addOption(private$..show)
            self$.addOption(private$..inferWhich)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        alphaSig = function() private$..alphaSig$value,
        ssq = function() private$..ssq$value,
        interaction = function() private$..interaction$value,
        equalVar = function() private$..equalVar$value,
        Transform = function() private$..Transform$value,
        show = function() private$..show$value,
        inferWhich = function() private$..inferWhich$value),
    private = list(
        ..IV = NA,
        ..DV = NA,
        ..alphaSig = NA,
        ..ssq = NA,
        ..interaction = NA,
        ..equalVar = NA,
        ..Transform = NA,
        ..show = NA,
        ..inferWhich = NA)
)

BrawAnResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnResults",
    inherit = jmvcore::Group,
    active = list(
        graphHTML = function() private$.items[["graphHTML"]],
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]],
        debug = function() private$.items[["debug"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Analyze Data")
            self$add(jmvcore::Html$new(
                options=options,
                name="graphHTML",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                renderFun=".plotGraph",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="reportPlot",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))}))

BrawAnBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawAn",
                version = c(1,0,0),
                options = options,
                results = BrawAnResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' BrawStats:Analyze Data
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @param alphaSig .
#' @param ssq .
#' @param interaction .
#' @param equalVar .
#' @param Transform .
#' @param show .
#' @param inferWhich .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
BrawAn <- function(
    data,
    IV,
    DV,
    alphaSig = 0.05,
    ssq = "Type3",
    interaction = "no",
    equalVar = "yes",
    Transform = "None",
    show = "Compact",
    inferWhich = "2D") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawAn requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- BrawAnOptions$new(
        IV = IV,
        DV = DV,
        alphaSig = alphaSig,
        ssq = ssq,
        interaction = interaction,
        equalVar = equalVar,
        Transform = Transform,
        show = show,
        inferWhich = inferWhich)

    analysis <- BrawAnClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

