
# This file is automatically generated, you probably don't want to edit this

BrawLMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawLMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL,
            inferWhich = "r",
            whichR = "Unique",
            showHTML = TRUE, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawLM",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariables$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..inferWhich <- jmvcore::OptionList$new(
                "inferWhich",
                inferWhich,
                options=list(
                    "r",
                    "p"),
                default="r")
            private$..whichR <- jmvcore::OptionList$new(
                "whichR",
                whichR,
                options=list(
                    "Direct",
                    "Unique",
                    "Total",
                    "Full"),
                default="Unique")
            private$..showHTML <- jmvcore::OptionBool$new(
                "showHTML",
                showHTML,
                default=TRUE)

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..inferWhich)
            self$.addOption(private$..whichR)
            self$.addOption(private$..showHTML)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        inferWhich = function() private$..inferWhich$value,
        whichR = function() private$..whichR$value,
        showHTML = function() private$..showHTML$value),
    private = list(
        ..IV = NA,
        ..DV = NA,
        ..inferWhich = NA,
        ..whichR = NA,
        ..showHTML = NA)
)

BrawLMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawLMResults",
    inherit = jmvcore::Group,
    active = list(
        lmGraphHTML = function() private$.items[["lmGraphHTML"]],
        lmGraph = function() private$.items[["lmGraph"]],
        lmReport = function() private$.items[["lmReport"]],
        reportTableLM = function() private$.items[["reportTableLM"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Linear Models")
            self$add(jmvcore::Html$new(
                options=options,
                name="lmGraphHTML",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="lmGraph",
                title=" ",
                width=500,
                height=300,
                renderFun=".lmPlotGraph",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="lmReport",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="reportTableLM",
                title=" ",
                rows=1,
                columns=list(
                    list(
                        `name`="AIC", 
                        `type`="number"),
                    list(
                        `name`="Rsqr", 
                        `type`="number"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="model", 
                        `type`="text")),
                visible=TRUE))}))

BrawLMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawLMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawLM",
                version = c(1,0,0),
                options = options,
                results = BrawLMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' BrawStats:Linear Models
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @param inferWhich .
#' @param whichR .
#' @param showHTML .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$lmGraphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$lmGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$lmReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reportTableLM} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$reportTableLM$asDF}
#'
#' \code{as.data.frame(results$reportTableLM)}
#'
#' @export
BrawLM <- function(
    data,
    IV,
    DV,
    inferWhich = "r",
    whichR = "Unique",
    showHTML = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawLM requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- BrawLMOptions$new(
        IV = IV,
        DV = DV,
        inferWhich = inferWhich,
        whichR = whichR,
        showHTML = showHTML)

    analysis <- BrawLMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

