
# This file is automatically generated, you probably don't want to edit this

BrawSEMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSEMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            Stage5 = NULL,
            Stage4 = NULL,
            Stage3 = NULL,
            Stage2 = NULL,
            Stage1 = NULL,
            Stage5On = TRUE,
            Stage4On = TRUE,
            Stage3On = TRUE,
            Stage2On = TRUE,
            Stage1On = TRUE,
            causalDirection = "down",
            Depth = "d1",
            ShowType = "ES",
            addDest = NULL,
            addSource = NULL,
            removeDest = NULL,
            removeSource = NULL,
            onlySource = NULL,
            onlyDest = NULL,
            showHTML = TRUE, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSEM",
                requiresData=TRUE,
                ...)

            private$..Stage5 <- jmvcore::OptionVariables$new(
                "Stage5",
                Stage5)
            private$..Stage4 <- jmvcore::OptionVariables$new(
                "Stage4",
                Stage4)
            private$..Stage3 <- jmvcore::OptionVariables$new(
                "Stage3",
                Stage3)
            private$..Stage2 <- jmvcore::OptionVariables$new(
                "Stage2",
                Stage2)
            private$..Stage1 <- jmvcore::OptionVariables$new(
                "Stage1",
                Stage1)
            private$..Stage5On <- jmvcore::OptionBool$new(
                "Stage5On",
                Stage5On,
                default=TRUE)
            private$..Stage4On <- jmvcore::OptionBool$new(
                "Stage4On",
                Stage4On,
                default=TRUE)
            private$..Stage3On <- jmvcore::OptionBool$new(
                "Stage3On",
                Stage3On,
                default=TRUE)
            private$..Stage2On <- jmvcore::OptionBool$new(
                "Stage2On",
                Stage2On,
                default=TRUE)
            private$..Stage1On <- jmvcore::OptionBool$new(
                "Stage1On",
                Stage1On,
                default=TRUE)
            private$..causalDirection <- jmvcore::OptionList$new(
                "causalDirection",
                causalDirection,
                options=list(
                    "up",
                    "down"),
                default="down")
            private$..Depth <- jmvcore::OptionList$new(
                "Depth",
                Depth,
                options=list(
                    "d1",
                    "d2",
                    "all"),
                default="d1")
            private$..ShowType <- jmvcore::OptionList$new(
                "ShowType",
                ShowType,
                options=list(
                    "CF",
                    "ES",
                    "cov"),
                default="ES")
            private$..addDest <- jmvcore::OptionVariables$new(
                "addDest",
                addDest)
            private$..addSource <- jmvcore::OptionVariables$new(
                "addSource",
                addSource)
            private$..removeDest <- jmvcore::OptionVariables$new(
                "removeDest",
                removeDest)
            private$..removeSource <- jmvcore::OptionVariables$new(
                "removeSource",
                removeSource)
            private$..onlySource <- jmvcore::OptionVariables$new(
                "onlySource",
                onlySource)
            private$..onlyDest <- jmvcore::OptionVariables$new(
                "onlyDest",
                onlyDest)
            private$..showHTML <- jmvcore::OptionBool$new(
                "showHTML",
                showHTML,
                default=TRUE)

            self$.addOption(private$..Stage5)
            self$.addOption(private$..Stage4)
            self$.addOption(private$..Stage3)
            self$.addOption(private$..Stage2)
            self$.addOption(private$..Stage1)
            self$.addOption(private$..Stage5On)
            self$.addOption(private$..Stage4On)
            self$.addOption(private$..Stage3On)
            self$.addOption(private$..Stage2On)
            self$.addOption(private$..Stage1On)
            self$.addOption(private$..causalDirection)
            self$.addOption(private$..Depth)
            self$.addOption(private$..ShowType)
            self$.addOption(private$..addDest)
            self$.addOption(private$..addSource)
            self$.addOption(private$..removeDest)
            self$.addOption(private$..removeSource)
            self$.addOption(private$..onlySource)
            self$.addOption(private$..onlyDest)
            self$.addOption(private$..showHTML)
        }),
    active = list(
        Stage5 = function() private$..Stage5$value,
        Stage4 = function() private$..Stage4$value,
        Stage3 = function() private$..Stage3$value,
        Stage2 = function() private$..Stage2$value,
        Stage1 = function() private$..Stage1$value,
        Stage5On = function() private$..Stage5On$value,
        Stage4On = function() private$..Stage4On$value,
        Stage3On = function() private$..Stage3On$value,
        Stage2On = function() private$..Stage2On$value,
        Stage1On = function() private$..Stage1On$value,
        causalDirection = function() private$..causalDirection$value,
        Depth = function() private$..Depth$value,
        ShowType = function() private$..ShowType$value,
        addDest = function() private$..addDest$value,
        addSource = function() private$..addSource$value,
        removeDest = function() private$..removeDest$value,
        removeSource = function() private$..removeSource$value,
        onlySource = function() private$..onlySource$value,
        onlyDest = function() private$..onlyDest$value,
        showHTML = function() private$..showHTML$value),
    private = list(
        ..Stage5 = NA,
        ..Stage4 = NA,
        ..Stage3 = NA,
        ..Stage2 = NA,
        ..Stage1 = NA,
        ..Stage5On = NA,
        ..Stage4On = NA,
        ..Stage3On = NA,
        ..Stage2On = NA,
        ..Stage1On = NA,
        ..causalDirection = NA,
        ..Depth = NA,
        ..ShowType = NA,
        ..addDest = NA,
        ..addSource = NA,
        ..removeDest = NA,
        ..removeSource = NA,
        ..onlySource = NA,
        ..onlyDest = NA,
        ..showHTML = NA)
)

BrawSEMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSEMResults",
    inherit = jmvcore::Group,
    active = list(
        semGraphHTML = function() private$.items[["semGraphHTML"]],
        semGraph = function() private$.items[["semGraph"]],
        debug = function() private$.items[["debug"]],
        reportSEM = function() private$.items[["reportSEM"]],
        reportTableSEM = function() private$.items[["reportTableSEM"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Path Models")
            self$add(jmvcore::Html$new(
                options=options,
                name="semGraphHTML",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="semGraph",
                title=" ",
                width=500,
                height=300,
                renderFun=".semPlotGraph",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="reportSEM",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="reportTableSEM",
                title=" ",
                rows=1,
                columns=list(
                    list(
                        `name`="AIC", 
                        `type`="number"),
                    list(
                        `name`="AICc", 
                        `type`="number"),
                    list(
                        `name`="BIC", 
                        `type`="number"),
                    list(
                        `name`="Rsqr", 
                        `type`="number"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="k", 
                        `type`="number"),
                    list(
                        `name`="llr", 
                        `type`="number"),
                    list(
                        `name`="model", 
                        `type`="text")),
                visible=TRUE))}))

BrawSEMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSEMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSEM",
                version = c(1,0,0),
                options = options,
                results = BrawSEMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' BrawStats:Path Models
#'
#' 
#' @param data .
#' @param Stage5 .
#' @param Stage4 .
#' @param Stage3 .
#' @param Stage2 .
#' @param Stage1 .
#' @param Stage5On .
#' @param Stage4On .
#' @param Stage3On .
#' @param Stage2On .
#' @param Stage1On .
#' @param causalDirection .
#' @param Depth .
#' @param ShowType .
#' @param addDest .
#' @param addSource .
#' @param removeDest .
#' @param removeSource .
#' @param onlySource .
#' @param onlyDest .
#' @param showHTML .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$semGraphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$semGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reportSEM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reportTableSEM} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$reportTableSEM$asDF}
#'
#' \code{as.data.frame(results$reportTableSEM)}
#'
#' @export
BrawSEM <- function(
    data,
    Stage5,
    Stage4,
    Stage3,
    Stage2,
    Stage1,
    Stage5On = TRUE,
    Stage4On = TRUE,
    Stage3On = TRUE,
    Stage2On = TRUE,
    Stage1On = TRUE,
    causalDirection = "down",
    Depth = "d1",
    ShowType = "ES",
    addDest,
    addSource,
    removeDest,
    removeSource,
    onlySource,
    onlyDest,
    showHTML = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSEM requires jmvcore to be installed (restart may be required)")

    if ( ! missing(Stage5)) Stage5 <- jmvcore::resolveQuo(jmvcore::enquo(Stage5))
    if ( ! missing(Stage4)) Stage4 <- jmvcore::resolveQuo(jmvcore::enquo(Stage4))
    if ( ! missing(Stage3)) Stage3 <- jmvcore::resolveQuo(jmvcore::enquo(Stage3))
    if ( ! missing(Stage2)) Stage2 <- jmvcore::resolveQuo(jmvcore::enquo(Stage2))
    if ( ! missing(Stage1)) Stage1 <- jmvcore::resolveQuo(jmvcore::enquo(Stage1))
    if ( ! missing(addDest)) addDest <- jmvcore::resolveQuo(jmvcore::enquo(addDest))
    if ( ! missing(addSource)) addSource <- jmvcore::resolveQuo(jmvcore::enquo(addSource))
    if ( ! missing(removeDest)) removeDest <- jmvcore::resolveQuo(jmvcore::enquo(removeDest))
    if ( ! missing(removeSource)) removeSource <- jmvcore::resolveQuo(jmvcore::enquo(removeSource))
    if ( ! missing(onlySource)) onlySource <- jmvcore::resolveQuo(jmvcore::enquo(onlySource))
    if ( ! missing(onlyDest)) onlyDest <- jmvcore::resolveQuo(jmvcore::enquo(onlyDest))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(Stage5), Stage5, NULL),
            `if`( ! missing(Stage4), Stage4, NULL),
            `if`( ! missing(Stage3), Stage3, NULL),
            `if`( ! missing(Stage2), Stage2, NULL),
            `if`( ! missing(Stage1), Stage1, NULL),
            `if`( ! missing(addDest), addDest, NULL),
            `if`( ! missing(addSource), addSource, NULL),
            `if`( ! missing(removeDest), removeDest, NULL),
            `if`( ! missing(removeSource), removeSource, NULL),
            `if`( ! missing(onlySource), onlySource, NULL),
            `if`( ! missing(onlyDest), onlyDest, NULL))


    options <- BrawSEMOptions$new(
        Stage5 = Stage5,
        Stage4 = Stage4,
        Stage3 = Stage3,
        Stage2 = Stage2,
        Stage1 = Stage1,
        Stage5On = Stage5On,
        Stage4On = Stage4On,
        Stage3On = Stage3On,
        Stage2On = Stage2On,
        Stage1On = Stage1On,
        causalDirection = causalDirection,
        Depth = Depth,
        ShowType = ShowType,
        addDest = addDest,
        addSource = addSource,
        removeDest = removeDest,
        removeSource = removeSource,
        onlySource = onlySource,
        onlyDest = onlyDest,
        showHTML = showHTML)

    analysis <- BrawSEMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

