
# This file is automatically generated, you probably don't want to edit this

BrawAnOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL,
            alphaSig = 0.05,
            ssq = "Type3",
            interaction = "no",
            equalVar = "yes",
            Transform = "None",
            likelihoodType = "Populations",
            likelihoodCutaway = "cutaway",
            likelihoodUsePrior = "none",
            priorPDF = "Exp",
            priorRZ = "z",
            priorLambda = 0.3,
            priorNullP = 0,
            showSampleType = "Compact",
            singleVar1 = "rs",
            singleVar2 = "p",
            showInferParam = "Basic",
            showInferDimension = "1D", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawAn",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariables$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..alphaSig <- jmvcore::OptionNumber$new(
                "alphaSig",
                alphaSig,
                default=0.05)
            private$..ssq <- jmvcore::OptionList$new(
                "ssq",
                ssq,
                options=list(
                    "Type1",
                    "Type2",
                    "Type3"),
                default="Type3")
            private$..interaction <- jmvcore::OptionList$new(
                "interaction",
                interaction,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..equalVar <- jmvcore::OptionList$new(
                "equalVar",
                equalVar,
                options=list(
                    "no",
                    "yes"),
                default="yes")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..likelihoodType <- jmvcore::OptionList$new(
                "likelihoodType",
                likelihoodType,
                options=list(
                    "Samples",
                    "Populations"),
                default="Populations")
            private$..likelihoodCutaway <- jmvcore::OptionList$new(
                "likelihoodCutaway",
                likelihoodCutaway,
                options=list(
                    "all",
                    "cutaway"),
                default="cutaway")
            private$..likelihoodUsePrior <- jmvcore::OptionList$new(
                "likelihoodUsePrior",
                likelihoodUsePrior,
                options=list(
                    "none",
                    "world",
                    "prior"),
                default="none")
            private$..priorPDF <- jmvcore::OptionList$new(
                "priorPDF",
                priorPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Exp")
            private$..priorRZ <- jmvcore::OptionList$new(
                "priorRZ",
                priorRZ,
                options=list(
                    "r",
                    "z"),
                default="z")
            private$..priorLambda <- jmvcore::OptionNumber$new(
                "priorLambda",
                priorLambda,
                default=0.3)
            private$..priorNullP <- jmvcore::OptionNumber$new(
                "priorNullP",
                priorNullP,
                default=0)
            private$..showSampleType <- jmvcore::OptionList$new(
                "showSampleType",
                showSampleType,
                options=list(
                    "Compact",
                    "Sample",
                    "Describe",
                    "Infer",
                    "Likelihood"),
                default="Compact")
            private$..singleVar1 <- jmvcore::OptionList$new(
                "singleVar1",
                singleVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..singleVar2 <- jmvcore::OptionList$new(
                "singleVar2",
                singleVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..showInferParam <- jmvcore::OptionList$new(
                "showInferParam",
                showInferParam,
                options=list(
                    "Basic",
                    "Custom"),
                default="Basic")
            private$..showInferDimension <- jmvcore::OptionList$new(
                "showInferDimension",
                showInferDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..alphaSig)
            self$.addOption(private$..ssq)
            self$.addOption(private$..interaction)
            self$.addOption(private$..equalVar)
            self$.addOption(private$..Transform)
            self$.addOption(private$..likelihoodType)
            self$.addOption(private$..likelihoodCutaway)
            self$.addOption(private$..likelihoodUsePrior)
            self$.addOption(private$..priorPDF)
            self$.addOption(private$..priorRZ)
            self$.addOption(private$..priorLambda)
            self$.addOption(private$..priorNullP)
            self$.addOption(private$..showSampleType)
            self$.addOption(private$..singleVar1)
            self$.addOption(private$..singleVar2)
            self$.addOption(private$..showInferParam)
            self$.addOption(private$..showInferDimension)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        alphaSig = function() private$..alphaSig$value,
        ssq = function() private$..ssq$value,
        interaction = function() private$..interaction$value,
        equalVar = function() private$..equalVar$value,
        Transform = function() private$..Transform$value,
        likelihoodType = function() private$..likelihoodType$value,
        likelihoodCutaway = function() private$..likelihoodCutaway$value,
        likelihoodUsePrior = function() private$..likelihoodUsePrior$value,
        priorPDF = function() private$..priorPDF$value,
        priorRZ = function() private$..priorRZ$value,
        priorLambda = function() private$..priorLambda$value,
        priorNullP = function() private$..priorNullP$value,
        showSampleType = function() private$..showSampleType$value,
        singleVar1 = function() private$..singleVar1$value,
        singleVar2 = function() private$..singleVar2$value,
        showInferParam = function() private$..showInferParam$value,
        showInferDimension = function() private$..showInferDimension$value),
    private = list(
        ..IV = NA,
        ..DV = NA,
        ..alphaSig = NA,
        ..ssq = NA,
        ..interaction = NA,
        ..equalVar = NA,
        ..Transform = NA,
        ..likelihoodType = NA,
        ..likelihoodCutaway = NA,
        ..likelihoodUsePrior = NA,
        ..priorPDF = NA,
        ..priorRZ = NA,
        ..priorLambda = NA,
        ..priorNullP = NA,
        ..showSampleType = NA,
        ..singleVar1 = NA,
        ..singleVar2 = NA,
        ..showInferParam = NA,
        ..showInferDimension = NA)
)

BrawAnResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnResults",
    inherit = jmvcore::Group,
    active = list(
        graphHTML = function() private$.items[["graphHTML"]],
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]],
        debug = function() private$.items[["debug"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Analyze Data")
            self$add(jmvcore::Html$new(
                options=options,
                name="graphHTML",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                renderFun=".plotGraph",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="reportPlot",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))}))

BrawAnBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawAn",
                version = c(1,0,0),
                options = options,
                results = BrawAnResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' BrawStats:Analyze Data
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @param alphaSig .
#' @param ssq .
#' @param interaction .
#' @param equalVar .
#' @param Transform .
#' @param likelihoodType .
#' @param likelihoodCutaway .
#' @param likelihoodUsePrior .
#' @param priorPDF .
#' @param priorRZ .
#' @param priorLambda .
#' @param priorNullP .
#' @param showSampleType .
#' @param singleVar1 .
#' @param singleVar2 .
#' @param showInferParam .
#' @param showInferDimension .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
BrawAn <- function(
    data,
    IV,
    DV,
    alphaSig = 0.05,
    ssq = "Type3",
    interaction = "no",
    equalVar = "yes",
    Transform = "None",
    likelihoodType = "Populations",
    likelihoodCutaway = "cutaway",
    likelihoodUsePrior = "none",
    priorPDF = "Exp",
    priorRZ = "z",
    priorLambda = 0.3,
    priorNullP = 0,
    showSampleType = "Compact",
    singleVar1 = "rs",
    singleVar2 = "p",
    showInferParam = "Basic",
    showInferDimension = "1D") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawAn requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- BrawAnOptions$new(
        IV = IV,
        DV = DV,
        alphaSig = alphaSig,
        ssq = ssq,
        interaction = interaction,
        equalVar = equalVar,
        Transform = Transform,
        likelihoodType = likelihoodType,
        likelihoodCutaway = likelihoodCutaway,
        likelihoodUsePrior = likelihoodUsePrior,
        priorPDF = priorPDF,
        priorRZ = priorRZ,
        priorLambda = priorLambda,
        priorNullP = priorNullP,
        showSampleType = showSampleType,
        singleVar1 = singleVar1,
        singleVar2 = singleVar2,
        showInferParam = showInferParam,
        showInferDimension = showInferDimension)

    analysis <- BrawAnClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

