
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            planOptions = NULL,
            presetDV = "Blank",
            presetIV = "Blank",
            presetIV2 = "none",
            presetWorld = "simple",
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 0,
            DVnlevs = 7,
            DViqr = 4,
            DVncats = 2,
            DVcases = "C1,C2",
            DVprops = "1,1",
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 0,
            IVnlevs = 7,
            IViqr = 4,
            IVncats = 2,
            IVcases = "C1,C2",
            IVprops = "1,1",
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 0,
            IV2nlevs = 7,
            IV2iqr = 4,
            IV2ncats = 2,
            IV2cases = "C1,C2",
            IV2props = "1,1",
            EffectSize1 = 0,
            EffectSize2 = 0,
            EffectSize3 = 0,
            EffectSize12 = 0,
            Heteroscedasticity = 0,
            Residuals = "normal",
            WorldOn = FALSE,
            WorldPDF = "Single",
            WorldRZ = NULL,
            WorldLambda = 0.3,
            WorldNullP = 0.5,
            SampleSize = 42,
            SampleSizeM = 42,
            SampleSpreadOn = FALSE,
            SampleGamma = 1.56,
            SampleMethod = "Random",
            SampleUsage1 = "Between",
            SampleUsage2 = "Between",
            Dependence = 0,
            Outliers = 0,
            NonResponse = 0,
            LimitRange = "no",
            RangeMin = -3,
            RangeMax = 3,
            Cheating = "None",
            CheatingAttempts = 5,
            ReplicationOn = FALSE,
            ReplicationPower = 0.8,
            ReplicationPrior = "None",
            ReplicationAttempts = 1,
            ReplicationDecision = "Cautious",
            ReplicationAlpha = 0.05,
            ReplicationSign = "yes",
            ReplicationSigOriginal = "yes",
            alphaSig = 0.05,
            ssq = "Type3",
            interaction = "no",
            equalVar = "yes",
            Transform = "None",
            likelihoodType = "Populations",
            likelihoodCutaway = "cutaway",
            likelihoodUsePrior = "none",
            priorPDF = "Exp",
            priorRZ = "z",
            priorLambda = 0.3,
            priorNullP = 0,
            MetaAnalysisOn = FALSE,
            MetaAnalysisType = "random",
            MetaAnalysisNulls = "yes",
            MetaAnalysisBias = "yes",
            MetaAnalysisNStudies = 10,
            MetaAnalysisStudiesSig = "sigOnly",
            showHypothesisBtn = NULL,
            showHypothesisType = "plan",
            makeSampleBtn = FALSE,
            numberSamples = 100,
            makeMultipleBtn = NULL,
            singleVar1 = "rs",
            singleVar2 = "p",
            multipleVar1 = "rs",
            multipleVar2 = "p",
            showSampleType = "Compact",
            showInferParam = "Basic",
            showInferDimension = "1D",
            showMultipleParam = "Basic",
            showMultipleDimension = "1D",
            exploreNPointsH = 13,
            exploreNPointsD = 13,
            exploreNPointsA = 13,
            exploreNPointsM = 13,
            exploreMinValH = "-0.9",
            exploreMaxValH = "0.9",
            exploreMinValD = "10",
            exploreMaxValD = "250",
            exploreMinValA = "0.001",
            exploreMaxValM = "0.5",
            exploreMinValM = "0.001",
            exploreMaxValA = "0.5",
            exploreXLogH = FALSE,
            exploreXLogD = FALSE,
            exploreXLogA = FALSE,
            exploreXLogM = FALSE,
            numberExplores = 50,
            makeExploreBtn = NULL,
            exploreMode = "designExplore",
            hypothesisExploreList = NULL,
            designExploreList = NULL,
            analysisExploreList = NULL,
            moreExploreList = NULL,
            showExploreParam = "Basic",
            exploreVar1 = "rs",
            exploreVar2 = "p",
            showExploreDimension = "1D",
            whichShowMultiple = "all",
            showJamovi = FALSE,
            showHTML = TRUE,
            doProject1aBtn = NULL,
            doProject1bBtn = NULL,
            doProject1cBtn = NULL,
            doProject1dBtn = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..planOptions <- jmvcore::OptionList$new(
                "planOptions",
                planOptions,
                options=list(
                    "planH",
                    "planD",
                    "planA",
                    "planM"))
            private$..presetDV <- jmvcore::OptionList$new(
                "presetDV",
                presetDV,
                options=list(
                    "Blank",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Happiness",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="Blank")
            private$..presetIV <- jmvcore::OptionList$new(
                "presetIV",
                presetIV,
                options=list(
                    "Blank",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Happiness",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="Blank")
            private$..presetIV2 <- jmvcore::OptionList$new(
                "presetIV2",
                presetIV2,
                options=list(
                    "none",
                    "IV2",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Happiness",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="none")
            private$..presetWorld <- jmvcore::OptionList$new(
                "presetWorld",
                presetWorld,
                options=list(
                    "psych",
                    "simple"),
                default="simple")
            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=0)
            private$..DVnlevs <- jmvcore::OptionNumber$new(
                "DVnlevs",
                DVnlevs,
                default=7)
            private$..DViqr <- jmvcore::OptionNumber$new(
                "DViqr",
                DViqr,
                default=4)
            private$..DVncats <- jmvcore::OptionNumber$new(
                "DVncats",
                DVncats,
                default=2)
            private$..DVcases <- jmvcore::OptionString$new(
                "DVcases",
                DVcases,
                default="C1,C2")
            private$..DVprops <- jmvcore::OptionString$new(
                "DVprops",
                DVprops,
                default="1,1")
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=0)
            private$..IVnlevs <- jmvcore::OptionNumber$new(
                "IVnlevs",
                IVnlevs,
                default=7)
            private$..IViqr <- jmvcore::OptionNumber$new(
                "IViqr",
                IViqr,
                default=4)
            private$..IVncats <- jmvcore::OptionNumber$new(
                "IVncats",
                IVncats,
                default=2)
            private$..IVcases <- jmvcore::OptionString$new(
                "IVcases",
                IVcases,
                default="C1,C2")
            private$..IVprops <- jmvcore::OptionString$new(
                "IVprops",
                IVprops,
                default="1,1")
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=0)
            private$..IV2nlevs <- jmvcore::OptionNumber$new(
                "IV2nlevs",
                IV2nlevs,
                default=7)
            private$..IV2iqr <- jmvcore::OptionNumber$new(
                "IV2iqr",
                IV2iqr,
                default=4)
            private$..IV2ncats <- jmvcore::OptionNumber$new(
                "IV2ncats",
                IV2ncats,
                default=2)
            private$..IV2cases <- jmvcore::OptionString$new(
                "IV2cases",
                IV2cases,
                default="C1,C2")
            private$..IV2props <- jmvcore::OptionString$new(
                "IV2props",
                IV2props,
                default="1,1")
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0)
            private$..Heteroscedasticity <- jmvcore::OptionNumber$new(
                "Heteroscedasticity",
                Heteroscedasticity,
                default=0)
            private$..Residuals <- jmvcore::OptionList$new(
                "Residuals",
                Residuals,
                options=list(
                    "normal",
                    "skewed",
                    "uniform",
                    "cauchy"),
                default="normal")
            private$..WorldOn <- jmvcore::OptionBool$new(
                "WorldOn",
                WorldOn,
                default=FALSE)
            private$..WorldPDF <- jmvcore::OptionList$new(
                "WorldPDF",
                WorldPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Single")
            private$..WorldRZ <- jmvcore::OptionList$new(
                "WorldRZ",
                WorldRZ,
                options=list(
                    "r",
                    "z"))
            private$..WorldLambda <- jmvcore::OptionNumber$new(
                "WorldLambda",
                WorldLambda,
                default=0.3)
            private$..WorldNullP <- jmvcore::OptionNumber$new(
                "WorldNullP",
                WorldNullP,
                default=0.5)
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleSizeM <- jmvcore::OptionNumber$new(
                "SampleSizeM",
                SampleSizeM,
                default=42)
            private$..SampleSpreadOn <- jmvcore::OptionBool$new(
                "SampleSpreadOn",
                SampleSpreadOn,
                default=FALSE)
            private$..SampleGamma <- jmvcore::OptionNumber$new(
                "SampleGamma",
                SampleGamma,
                default=1.56)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Cluster",
                    "Convenience"),
                default="Random")
            private$..SampleUsage1 <- jmvcore::OptionList$new(
                "SampleUsage1",
                SampleUsage1,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..SampleUsage2 <- jmvcore::OptionList$new(
                "SampleUsage2",
                SampleUsage2,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..NonResponse <- jmvcore::OptionNumber$new(
                "NonResponse",
                NonResponse,
                default=0)
            private$..LimitRange <- jmvcore::OptionList$new(
                "LimitRange",
                LimitRange,
                options=list(
                    "yes",
                    "no"),
                default="no")
            private$..RangeMin <- jmvcore::OptionNumber$new(
                "RangeMin",
                RangeMin,
                default=-3)
            private$..RangeMax <- jmvcore::OptionNumber$new(
                "RangeMax",
                RangeMax,
                default=3)
            private$..Cheating <- jmvcore::OptionList$new(
                "Cheating",
                Cheating,
                options=list(
                    "None",
                    "Grow",
                    "Prune",
                    "Replace",
                    "Retry"),
                default="None")
            private$..CheatingAttempts <- jmvcore::OptionNumber$new(
                "CheatingAttempts",
                CheatingAttempts,
                default=5)
            private$..ReplicationOn <- jmvcore::OptionBool$new(
                "ReplicationOn",
                ReplicationOn,
                default=FALSE)
            private$..ReplicationPower <- jmvcore::OptionNumber$new(
                "ReplicationPower",
                ReplicationPower,
                default=0.8)
            private$..ReplicationPrior <- jmvcore::OptionList$new(
                "ReplicationPrior",
                ReplicationPrior,
                options=list(
                    "None",
                    "World",
                    "Prior"),
                default="None")
            private$..ReplicationAttempts <- jmvcore::OptionNumber$new(
                "ReplicationAttempts",
                ReplicationAttempts,
                default=1)
            private$..ReplicationDecision <- jmvcore::OptionList$new(
                "ReplicationDecision",
                ReplicationDecision,
                options=list(
                    "Cautious",
                    "Last",
                    "Median",
                    "SmallP",
                    "LargeN"),
                default="Cautious")
            private$..ReplicationAlpha <- jmvcore::OptionNumber$new(
                "ReplicationAlpha",
                ReplicationAlpha,
                default=0.05)
            private$..ReplicationSign <- jmvcore::OptionList$new(
                "ReplicationSign",
                ReplicationSign,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..ReplicationSigOriginal <- jmvcore::OptionList$new(
                "ReplicationSigOriginal",
                ReplicationSigOriginal,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..alphaSig <- jmvcore::OptionNumber$new(
                "alphaSig",
                alphaSig,
                default=0.05)
            private$..ssq <- jmvcore::OptionList$new(
                "ssq",
                ssq,
                options=list(
                    "Type1",
                    "Type2",
                    "Type3"),
                default="Type3")
            private$..interaction <- jmvcore::OptionList$new(
                "interaction",
                interaction,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..equalVar <- jmvcore::OptionList$new(
                "equalVar",
                equalVar,
                options=list(
                    "no",
                    "yes"),
                default="yes")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..likelihoodType <- jmvcore::OptionList$new(
                "likelihoodType",
                likelihoodType,
                options=list(
                    "Samples",
                    "Populations"),
                default="Populations")
            private$..likelihoodCutaway <- jmvcore::OptionList$new(
                "likelihoodCutaway",
                likelihoodCutaway,
                options=list(
                    "all",
                    "cutaway"),
                default="cutaway")
            private$..likelihoodUsePrior <- jmvcore::OptionList$new(
                "likelihoodUsePrior",
                likelihoodUsePrior,
                options=list(
                    "none",
                    "world",
                    "prior"),
                default="none")
            private$..priorPDF <- jmvcore::OptionList$new(
                "priorPDF",
                priorPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Exp")
            private$..priorRZ <- jmvcore::OptionList$new(
                "priorRZ",
                priorRZ,
                options=list(
                    "r",
                    "z"),
                default="z")
            private$..priorLambda <- jmvcore::OptionNumber$new(
                "priorLambda",
                priorLambda,
                default=0.3)
            private$..priorNullP <- jmvcore::OptionNumber$new(
                "priorNullP",
                priorNullP,
                default=0)
            private$..MetaAnalysisOn <- jmvcore::OptionBool$new(
                "MetaAnalysisOn",
                MetaAnalysisOn,
                default=FALSE)
            private$..MetaAnalysisType <- jmvcore::OptionList$new(
                "MetaAnalysisType",
                MetaAnalysisType,
                options=list(
                    "random",
                    "fixed"),
                default="random")
            private$..MetaAnalysisNulls <- jmvcore::OptionList$new(
                "MetaAnalysisNulls",
                MetaAnalysisNulls,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..MetaAnalysisBias <- jmvcore::OptionList$new(
                "MetaAnalysisBias",
                MetaAnalysisBias,
                options=list(
                    "yes",
                    "no"),
                default="yes")
            private$..MetaAnalysisNStudies <- jmvcore::OptionNumber$new(
                "MetaAnalysisNStudies",
                MetaAnalysisNStudies,
                default=10)
            private$..MetaAnalysisStudiesSig <- jmvcore::OptionList$new(
                "MetaAnalysisStudiesSig",
                MetaAnalysisStudiesSig,
                options=list(
                    "all",
                    "sigOnly"),
                default="sigOnly")
            private$..showHypothesisBtn <- jmvcore::OptionAction$new(
                "showHypothesisBtn",
                showHypothesisBtn)
            private$..showHypothesisType <- jmvcore::OptionList$new(
                "showHypothesisType",
                showHypothesisType,
                options=list(
                    "plan",
                    "prediction"),
                default="plan")
            private$..makeSampleBtn <- jmvcore::OptionAction$new(
                "makeSampleBtn",
                makeSampleBtn,
                default=FALSE)
            private$..numberSamples <- jmvcore::OptionNumber$new(
                "numberSamples",
                numberSamples,
                default=100)
            private$..makeMultipleBtn <- jmvcore::OptionAction$new(
                "makeMultipleBtn",
                makeMultipleBtn)
            private$..singleVar1 <- jmvcore::OptionList$new(
                "singleVar1",
                singleVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..singleVar2 <- jmvcore::OptionList$new(
                "singleVar2",
                singleVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..multipleVar1 <- jmvcore::OptionList$new(
                "multipleVar1",
                multipleVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..multipleVar2 <- jmvcore::OptionList$new(
                "multipleVar2",
                multipleVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..showSampleType <- jmvcore::OptionList$new(
                "showSampleType",
                showSampleType,
                options=list(
                    "Compact",
                    "Sample",
                    "Describe",
                    "Infer",
                    "Likelihood"),
                default="Compact")
            private$..showInferParam <- jmvcore::OptionList$new(
                "showInferParam",
                showInferParam,
                options=list(
                    "Basic",
                    "Custom"),
                default="Basic")
            private$..showInferDimension <- jmvcore::OptionList$new(
                "showInferDimension",
                showInferDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..showMultipleParam <- jmvcore::OptionList$new(
                "showMultipleParam",
                showMultipleParam,
                options=list(
                    "Basic",
                    "Custom",
                    "p(sig)",
                    "NHST",
                    "Hits",
                    "Misses",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..showMultipleDimension <- jmvcore::OptionList$new(
                "showMultipleDimension",
                showMultipleDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..exploreNPointsH <- jmvcore::OptionNumber$new(
                "exploreNPointsH",
                exploreNPointsH,
                default=13)
            private$..exploreNPointsD <- jmvcore::OptionNumber$new(
                "exploreNPointsD",
                exploreNPointsD,
                default=13)
            private$..exploreNPointsA <- jmvcore::OptionNumber$new(
                "exploreNPointsA",
                exploreNPointsA,
                default=13)
            private$..exploreNPointsM <- jmvcore::OptionNumber$new(
                "exploreNPointsM",
                exploreNPointsM,
                default=13)
            private$..exploreMinValH <- jmvcore::OptionString$new(
                "exploreMinValH",
                exploreMinValH,
                default="-0.9")
            private$..exploreMaxValH <- jmvcore::OptionString$new(
                "exploreMaxValH",
                exploreMaxValH,
                default="0.9")
            private$..exploreMinValD <- jmvcore::OptionString$new(
                "exploreMinValD",
                exploreMinValD,
                default="10")
            private$..exploreMaxValD <- jmvcore::OptionString$new(
                "exploreMaxValD",
                exploreMaxValD,
                default="250")
            private$..exploreMinValA <- jmvcore::OptionString$new(
                "exploreMinValA",
                exploreMinValA,
                default="0.001")
            private$..exploreMaxValM <- jmvcore::OptionString$new(
                "exploreMaxValM",
                exploreMaxValM,
                default="0.5")
            private$..exploreMinValM <- jmvcore::OptionString$new(
                "exploreMinValM",
                exploreMinValM,
                default="0.001")
            private$..exploreMaxValA <- jmvcore::OptionString$new(
                "exploreMaxValA",
                exploreMaxValA,
                default="0.5")
            private$..exploreXLogH <- jmvcore::OptionBool$new(
                "exploreXLogH",
                exploreXLogH,
                default=FALSE)
            private$..exploreXLogD <- jmvcore::OptionBool$new(
                "exploreXLogD",
                exploreXLogD,
                default=FALSE)
            private$..exploreXLogA <- jmvcore::OptionBool$new(
                "exploreXLogA",
                exploreXLogA,
                default=FALSE)
            private$..exploreXLogM <- jmvcore::OptionBool$new(
                "exploreXLogM",
                exploreXLogM,
                default=FALSE)
            private$..numberExplores <- jmvcore::OptionNumber$new(
                "numberExplores",
                numberExplores,
                default=50)
            private$..makeExploreBtn <- jmvcore::OptionAction$new(
                "makeExploreBtn",
                makeExploreBtn)
            private$..exploreMode <- jmvcore::OptionList$new(
                "exploreMode",
                exploreMode,
                options=list(
                    "hypothesisExplore",
                    "designExplore",
                    "analysisExplore",
                    "moreExplore"),
                default="designExplore")
            private$..hypothesisExploreList <- jmvcore::OptionList$new(
                "hypothesisExploreList",
                hypothesisExploreList,
                options=list(
                    "rIV",
                    "rIVIV2",
                    "rIVIV2DV",
                    "Heteroscedasticity",
                    "blank0h",
                    "IVType",
                    "IVskew",
                    "IVkurtosis",
                    "IVlevels",
                    "IVcats",
                    "IVprops",
                    "DVType",
                    "DVskew",
                    "DVkurtosis",
                    "DVcats",
                    "DVprops",
                    "blank1h",
                    "lambda",
                    "pNull",
                    "blank2h"))
            private$..designExploreList <- jmvcore::OptionList$new(
                "designExploreList",
                designExploreList,
                options=list(
                    "n",
                    "Method",
                    "Usage",
                    "blank1d",
                    "Dependence",
                    "Outliers",
                    "NonResponse",
                    "IVRangeC",
                    "IVRangeE",
                    "blank1e",
                    "Cheating",
                    "CheatingAmount"))
            private$..analysisExploreList <- jmvcore::OptionList$new(
                "analysisExploreList",
                analysisExploreList,
                options=list(
                    "Alpha",
                    "Transform",
                    "Welch",
                    "InteractionOn"))
            private$..moreExploreList <- jmvcore::OptionList$new(
                "moreExploreList",
                moreExploreList,
                options=list(
                    "Power",
                    "Keep",
                    "Repeats"))
            private$..showExploreParam <- jmvcore::OptionList$new(
                "showExploreParam",
                showExploreParam,
                options=list(
                    "Basic",
                    "Custom",
                    "p(sig)",
                    "NHST",
                    "Hits",
                    "Misses",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..exploreVar1 <- jmvcore::OptionList$new(
                "exploreVar1",
                exploreVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..exploreVar2 <- jmvcore::OptionList$new(
                "exploreVar2",
                exploreVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "ws",
                    "wp",
                    "nw",
                    "blank2",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..showExploreDimension <- jmvcore::OptionList$new(
                "showExploreDimension",
                showExploreDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..whichShowMultiple <- jmvcore::OptionList$new(
                "whichShowMultiple",
                whichShowMultiple,
                options=list(
                    "direct",
                    "unique",
                    "total",
                    "all"),
                default="all")
            private$..sendSample <- jmvcore::OptionOutput$new(
                "sendSample")
            private$..sendMultiple <- jmvcore::OptionOutput$new(
                "sendMultiple")
            private$..showJamovi <- jmvcore::OptionBool$new(
                "showJamovi",
                showJamovi,
                default=FALSE)
            private$..showHTML <- jmvcore::OptionBool$new(
                "showHTML",
                showHTML,
                default=TRUE)
            private$..doProject1aBtn <- jmvcore::OptionAction$new(
                "doProject1aBtn",
                doProject1aBtn)
            private$..doProject1bBtn <- jmvcore::OptionAction$new(
                "doProject1bBtn",
                doProject1bBtn)
            private$..doProject1cBtn <- jmvcore::OptionAction$new(
                "doProject1cBtn",
                doProject1cBtn)
            private$..doProject1dBtn <- jmvcore::OptionAction$new(
                "doProject1dBtn",
                doProject1dBtn)

            self$.addOption(private$..planOptions)
            self$.addOption(private$..presetDV)
            self$.addOption(private$..presetIV)
            self$.addOption(private$..presetIV2)
            self$.addOption(private$..presetWorld)
            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..DVnlevs)
            self$.addOption(private$..DViqr)
            self$.addOption(private$..DVncats)
            self$.addOption(private$..DVcases)
            self$.addOption(private$..DVprops)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IVnlevs)
            self$.addOption(private$..IViqr)
            self$.addOption(private$..IVncats)
            self$.addOption(private$..IVcases)
            self$.addOption(private$..IVprops)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..IV2nlevs)
            self$.addOption(private$..IV2iqr)
            self$.addOption(private$..IV2ncats)
            self$.addOption(private$..IV2cases)
            self$.addOption(private$..IV2props)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..Heteroscedasticity)
            self$.addOption(private$..Residuals)
            self$.addOption(private$..WorldOn)
            self$.addOption(private$..WorldPDF)
            self$.addOption(private$..WorldRZ)
            self$.addOption(private$..WorldLambda)
            self$.addOption(private$..WorldNullP)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleSizeM)
            self$.addOption(private$..SampleSpreadOn)
            self$.addOption(private$..SampleGamma)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..SampleUsage1)
            self$.addOption(private$..SampleUsage2)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..NonResponse)
            self$.addOption(private$..LimitRange)
            self$.addOption(private$..RangeMin)
            self$.addOption(private$..RangeMax)
            self$.addOption(private$..Cheating)
            self$.addOption(private$..CheatingAttempts)
            self$.addOption(private$..ReplicationOn)
            self$.addOption(private$..ReplicationPower)
            self$.addOption(private$..ReplicationPrior)
            self$.addOption(private$..ReplicationAttempts)
            self$.addOption(private$..ReplicationDecision)
            self$.addOption(private$..ReplicationAlpha)
            self$.addOption(private$..ReplicationSign)
            self$.addOption(private$..ReplicationSigOriginal)
            self$.addOption(private$..alphaSig)
            self$.addOption(private$..ssq)
            self$.addOption(private$..interaction)
            self$.addOption(private$..equalVar)
            self$.addOption(private$..Transform)
            self$.addOption(private$..likelihoodType)
            self$.addOption(private$..likelihoodCutaway)
            self$.addOption(private$..likelihoodUsePrior)
            self$.addOption(private$..priorPDF)
            self$.addOption(private$..priorRZ)
            self$.addOption(private$..priorLambda)
            self$.addOption(private$..priorNullP)
            self$.addOption(private$..MetaAnalysisOn)
            self$.addOption(private$..MetaAnalysisType)
            self$.addOption(private$..MetaAnalysisNulls)
            self$.addOption(private$..MetaAnalysisBias)
            self$.addOption(private$..MetaAnalysisNStudies)
            self$.addOption(private$..MetaAnalysisStudiesSig)
            self$.addOption(private$..showHypothesisBtn)
            self$.addOption(private$..showHypothesisType)
            self$.addOption(private$..makeSampleBtn)
            self$.addOption(private$..numberSamples)
            self$.addOption(private$..makeMultipleBtn)
            self$.addOption(private$..singleVar1)
            self$.addOption(private$..singleVar2)
            self$.addOption(private$..multipleVar1)
            self$.addOption(private$..multipleVar2)
            self$.addOption(private$..showSampleType)
            self$.addOption(private$..showInferParam)
            self$.addOption(private$..showInferDimension)
            self$.addOption(private$..showMultipleParam)
            self$.addOption(private$..showMultipleDimension)
            self$.addOption(private$..exploreNPointsH)
            self$.addOption(private$..exploreNPointsD)
            self$.addOption(private$..exploreNPointsA)
            self$.addOption(private$..exploreNPointsM)
            self$.addOption(private$..exploreMinValH)
            self$.addOption(private$..exploreMaxValH)
            self$.addOption(private$..exploreMinValD)
            self$.addOption(private$..exploreMaxValD)
            self$.addOption(private$..exploreMinValA)
            self$.addOption(private$..exploreMaxValM)
            self$.addOption(private$..exploreMinValM)
            self$.addOption(private$..exploreMaxValA)
            self$.addOption(private$..exploreXLogH)
            self$.addOption(private$..exploreXLogD)
            self$.addOption(private$..exploreXLogA)
            self$.addOption(private$..exploreXLogM)
            self$.addOption(private$..numberExplores)
            self$.addOption(private$..makeExploreBtn)
            self$.addOption(private$..exploreMode)
            self$.addOption(private$..hypothesisExploreList)
            self$.addOption(private$..designExploreList)
            self$.addOption(private$..analysisExploreList)
            self$.addOption(private$..moreExploreList)
            self$.addOption(private$..showExploreParam)
            self$.addOption(private$..exploreVar1)
            self$.addOption(private$..exploreVar2)
            self$.addOption(private$..showExploreDimension)
            self$.addOption(private$..whichShowMultiple)
            self$.addOption(private$..sendSample)
            self$.addOption(private$..sendMultiple)
            self$.addOption(private$..showJamovi)
            self$.addOption(private$..showHTML)
            self$.addOption(private$..doProject1aBtn)
            self$.addOption(private$..doProject1bBtn)
            self$.addOption(private$..doProject1cBtn)
            self$.addOption(private$..doProject1dBtn)
        }),
    active = list(
        planOptions = function() private$..planOptions$value,
        presetDV = function() private$..presetDV$value,
        presetIV = function() private$..presetIV$value,
        presetIV2 = function() private$..presetIV2$value,
        presetWorld = function() private$..presetWorld$value,
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        DVnlevs = function() private$..DVnlevs$value,
        DViqr = function() private$..DViqr$value,
        DVncats = function() private$..DVncats$value,
        DVcases = function() private$..DVcases$value,
        DVprops = function() private$..DVprops$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IVnlevs = function() private$..IVnlevs$value,
        IViqr = function() private$..IViqr$value,
        IVncats = function() private$..IVncats$value,
        IVcases = function() private$..IVcases$value,
        IVprops = function() private$..IVprops$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        IV2nlevs = function() private$..IV2nlevs$value,
        IV2iqr = function() private$..IV2iqr$value,
        IV2ncats = function() private$..IV2ncats$value,
        IV2cases = function() private$..IV2cases$value,
        IV2props = function() private$..IV2props$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        Heteroscedasticity = function() private$..Heteroscedasticity$value,
        Residuals = function() private$..Residuals$value,
        WorldOn = function() private$..WorldOn$value,
        WorldPDF = function() private$..WorldPDF$value,
        WorldRZ = function() private$..WorldRZ$value,
        WorldLambda = function() private$..WorldLambda$value,
        WorldNullP = function() private$..WorldNullP$value,
        SampleSize = function() private$..SampleSize$value,
        SampleSizeM = function() private$..SampleSizeM$value,
        SampleSpreadOn = function() private$..SampleSpreadOn$value,
        SampleGamma = function() private$..SampleGamma$value,
        SampleMethod = function() private$..SampleMethod$value,
        SampleUsage1 = function() private$..SampleUsage1$value,
        SampleUsage2 = function() private$..SampleUsage2$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        NonResponse = function() private$..NonResponse$value,
        LimitRange = function() private$..LimitRange$value,
        RangeMin = function() private$..RangeMin$value,
        RangeMax = function() private$..RangeMax$value,
        Cheating = function() private$..Cheating$value,
        CheatingAttempts = function() private$..CheatingAttempts$value,
        ReplicationOn = function() private$..ReplicationOn$value,
        ReplicationPower = function() private$..ReplicationPower$value,
        ReplicationPrior = function() private$..ReplicationPrior$value,
        ReplicationAttempts = function() private$..ReplicationAttempts$value,
        ReplicationDecision = function() private$..ReplicationDecision$value,
        ReplicationAlpha = function() private$..ReplicationAlpha$value,
        ReplicationSign = function() private$..ReplicationSign$value,
        ReplicationSigOriginal = function() private$..ReplicationSigOriginal$value,
        alphaSig = function() private$..alphaSig$value,
        ssq = function() private$..ssq$value,
        interaction = function() private$..interaction$value,
        equalVar = function() private$..equalVar$value,
        Transform = function() private$..Transform$value,
        likelihoodType = function() private$..likelihoodType$value,
        likelihoodCutaway = function() private$..likelihoodCutaway$value,
        likelihoodUsePrior = function() private$..likelihoodUsePrior$value,
        priorPDF = function() private$..priorPDF$value,
        priorRZ = function() private$..priorRZ$value,
        priorLambda = function() private$..priorLambda$value,
        priorNullP = function() private$..priorNullP$value,
        MetaAnalysisOn = function() private$..MetaAnalysisOn$value,
        MetaAnalysisType = function() private$..MetaAnalysisType$value,
        MetaAnalysisNulls = function() private$..MetaAnalysisNulls$value,
        MetaAnalysisBias = function() private$..MetaAnalysisBias$value,
        MetaAnalysisNStudies = function() private$..MetaAnalysisNStudies$value,
        MetaAnalysisStudiesSig = function() private$..MetaAnalysisStudiesSig$value,
        showHypothesisBtn = function() private$..showHypothesisBtn$value,
        showHypothesisType = function() private$..showHypothesisType$value,
        makeSampleBtn = function() private$..makeSampleBtn$value,
        numberSamples = function() private$..numberSamples$value,
        makeMultipleBtn = function() private$..makeMultipleBtn$value,
        singleVar1 = function() private$..singleVar1$value,
        singleVar2 = function() private$..singleVar2$value,
        multipleVar1 = function() private$..multipleVar1$value,
        multipleVar2 = function() private$..multipleVar2$value,
        showSampleType = function() private$..showSampleType$value,
        showInferParam = function() private$..showInferParam$value,
        showInferDimension = function() private$..showInferDimension$value,
        showMultipleParam = function() private$..showMultipleParam$value,
        showMultipleDimension = function() private$..showMultipleDimension$value,
        exploreNPointsH = function() private$..exploreNPointsH$value,
        exploreNPointsD = function() private$..exploreNPointsD$value,
        exploreNPointsA = function() private$..exploreNPointsA$value,
        exploreNPointsM = function() private$..exploreNPointsM$value,
        exploreMinValH = function() private$..exploreMinValH$value,
        exploreMaxValH = function() private$..exploreMaxValH$value,
        exploreMinValD = function() private$..exploreMinValD$value,
        exploreMaxValD = function() private$..exploreMaxValD$value,
        exploreMinValA = function() private$..exploreMinValA$value,
        exploreMaxValM = function() private$..exploreMaxValM$value,
        exploreMinValM = function() private$..exploreMinValM$value,
        exploreMaxValA = function() private$..exploreMaxValA$value,
        exploreXLogH = function() private$..exploreXLogH$value,
        exploreXLogD = function() private$..exploreXLogD$value,
        exploreXLogA = function() private$..exploreXLogA$value,
        exploreXLogM = function() private$..exploreXLogM$value,
        numberExplores = function() private$..numberExplores$value,
        makeExploreBtn = function() private$..makeExploreBtn$value,
        exploreMode = function() private$..exploreMode$value,
        hypothesisExploreList = function() private$..hypothesisExploreList$value,
        designExploreList = function() private$..designExploreList$value,
        analysisExploreList = function() private$..analysisExploreList$value,
        moreExploreList = function() private$..moreExploreList$value,
        showExploreParam = function() private$..showExploreParam$value,
        exploreVar1 = function() private$..exploreVar1$value,
        exploreVar2 = function() private$..exploreVar2$value,
        showExploreDimension = function() private$..showExploreDimension$value,
        whichShowMultiple = function() private$..whichShowMultiple$value,
        sendSample = function() private$..sendSample$value,
        sendMultiple = function() private$..sendMultiple$value,
        showJamovi = function() private$..showJamovi$value,
        showHTML = function() private$..showHTML$value,
        doProject1aBtn = function() private$..doProject1aBtn$value,
        doProject1bBtn = function() private$..doProject1bBtn$value,
        doProject1cBtn = function() private$..doProject1cBtn$value,
        doProject1dBtn = function() private$..doProject1dBtn$value),
    private = list(
        ..planOptions = NA,
        ..presetDV = NA,
        ..presetIV = NA,
        ..presetIV2 = NA,
        ..presetWorld = NA,
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..DVnlevs = NA,
        ..DViqr = NA,
        ..DVncats = NA,
        ..DVcases = NA,
        ..DVprops = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IVnlevs = NA,
        ..IViqr = NA,
        ..IVncats = NA,
        ..IVcases = NA,
        ..IVprops = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..IV2nlevs = NA,
        ..IV2iqr = NA,
        ..IV2ncats = NA,
        ..IV2cases = NA,
        ..IV2props = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..Heteroscedasticity = NA,
        ..Residuals = NA,
        ..WorldOn = NA,
        ..WorldPDF = NA,
        ..WorldRZ = NA,
        ..WorldLambda = NA,
        ..WorldNullP = NA,
        ..SampleSize = NA,
        ..SampleSizeM = NA,
        ..SampleSpreadOn = NA,
        ..SampleGamma = NA,
        ..SampleMethod = NA,
        ..SampleUsage1 = NA,
        ..SampleUsage2 = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..NonResponse = NA,
        ..LimitRange = NA,
        ..RangeMin = NA,
        ..RangeMax = NA,
        ..Cheating = NA,
        ..CheatingAttempts = NA,
        ..ReplicationOn = NA,
        ..ReplicationPower = NA,
        ..ReplicationPrior = NA,
        ..ReplicationAttempts = NA,
        ..ReplicationDecision = NA,
        ..ReplicationAlpha = NA,
        ..ReplicationSign = NA,
        ..ReplicationSigOriginal = NA,
        ..alphaSig = NA,
        ..ssq = NA,
        ..interaction = NA,
        ..equalVar = NA,
        ..Transform = NA,
        ..likelihoodType = NA,
        ..likelihoodCutaway = NA,
        ..likelihoodUsePrior = NA,
        ..priorPDF = NA,
        ..priorRZ = NA,
        ..priorLambda = NA,
        ..priorNullP = NA,
        ..MetaAnalysisOn = NA,
        ..MetaAnalysisType = NA,
        ..MetaAnalysisNulls = NA,
        ..MetaAnalysisBias = NA,
        ..MetaAnalysisNStudies = NA,
        ..MetaAnalysisStudiesSig = NA,
        ..showHypothesisBtn = NA,
        ..showHypothesisType = NA,
        ..makeSampleBtn = NA,
        ..numberSamples = NA,
        ..makeMultipleBtn = NA,
        ..singleVar1 = NA,
        ..singleVar2 = NA,
        ..multipleVar1 = NA,
        ..multipleVar2 = NA,
        ..showSampleType = NA,
        ..showInferParam = NA,
        ..showInferDimension = NA,
        ..showMultipleParam = NA,
        ..showMultipleDimension = NA,
        ..exploreNPointsH = NA,
        ..exploreNPointsD = NA,
        ..exploreNPointsA = NA,
        ..exploreNPointsM = NA,
        ..exploreMinValH = NA,
        ..exploreMaxValH = NA,
        ..exploreMinValD = NA,
        ..exploreMaxValD = NA,
        ..exploreMinValA = NA,
        ..exploreMaxValM = NA,
        ..exploreMinValM = NA,
        ..exploreMaxValA = NA,
        ..exploreXLogH = NA,
        ..exploreXLogD = NA,
        ..exploreXLogA = NA,
        ..exploreXLogM = NA,
        ..numberExplores = NA,
        ..makeExploreBtn = NA,
        ..exploreMode = NA,
        ..hypothesisExploreList = NA,
        ..designExploreList = NA,
        ..analysisExploreList = NA,
        ..moreExploreList = NA,
        ..showExploreParam = NA,
        ..exploreVar1 = NA,
        ..exploreVar2 = NA,
        ..showExploreDimension = NA,
        ..whichShowMultiple = NA,
        ..sendSample = NA,
        ..sendMultiple = NA,
        ..showJamovi = NA,
        ..showHTML = NA,
        ..doProject1aBtn = NA,
        ..doProject1bBtn = NA,
        ..doProject1cBtn = NA,
        ..doProject1dBtn = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        testHTML = function() private$.items[["testHTML"]],
        BrawStatsInstructions = function() private$.items[["BrawStatsInstructions"]],
        graphHTML = function() private$.items[["graphHTML"]],
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]],
        JamoviInstructions = function() private$.items[["JamoviInstructions"]],
        debug = function() private$.items[["debug"]],
        sendSample = function() private$.items[["sendSample"]],
        sendMultiple = function() private$.items[["sendMultiple"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Simulate Data",
                refs="brawstats book")
            self$add(jmvcore::Html$new(
                options=options,
                name="testHTML",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="BrawStatsInstructions",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="graphHTML",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=550,
                height=400,
                visible=FALSE,
                renderFun=".plotGraph",
                clearWith=list(
                    "showHypothesisBtn",
                    "showHypothesisType",
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "singleVar1",
                    "singleVar2",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "multipleVar1",
                    "multipleVar2",
                    "showMultipleDimension",
                    "makeExploreBtn",
                    "showExploreParam",
                    "exploreVar1",
                    "exploreVar2",
                    "showExploreDimension")))
            self$add(jmvcore::Html$new(
                options=options,
                name="reportPlot",
                title=" ",
                visible=TRUE,
                clearWith=list(
                    "showHypothesisBtn",
                    "showHypothesisType",
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "singleVar1",
                    "singleVar2",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "multipleVar1",
                    "multipleVar2",
                    "showMultipleDimension",
                    "makeExploreBtn",
                    "showExploreParam",
                    "exploreVar1",
                    "exploreVar2",
                    "showExploreDimension"),
                refs=list(
                    "brawstats",
                    "book")))
            self$add(jmvcore::Html$new(
                options=options,
                name="JamoviInstructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSample",
                measureType="nominal",
                varTitle="Sample",
                items=4,
                clearWith=list(
                    "makeSampleBtn")))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendMultiple",
                measureType="continuous",
                varTitle="Mult",
                items=3,
                clearWith=list(
                    "makeMultipleBtn")))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' BrawStats:Simulate Data
#'
#' 
#' @param planOptions .
#' @param presetDV .
#' @param presetIV .
#' @param presetIV2 .
#' @param presetWorld .
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param DVnlevs .
#' @param DViqr .
#' @param DVncats .
#' @param DVcases .
#' @param DVprops .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IVnlevs .
#' @param IViqr .
#' @param IVncats .
#' @param IVcases .
#' @param IVprops .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param IV2nlevs .
#' @param IV2iqr .
#' @param IV2ncats .
#' @param IV2cases .
#' @param IV2props .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param Heteroscedasticity .
#' @param Residuals .
#' @param WorldOn .
#' @param WorldPDF .
#' @param WorldRZ .
#' @param WorldLambda .
#' @param WorldNullP .
#' @param SampleSize .
#' @param SampleSizeM .
#' @param SampleSpreadOn .
#' @param SampleGamma .
#' @param SampleMethod .
#' @param SampleUsage1 .
#' @param SampleUsage2 .
#' @param Dependence .
#' @param Outliers .
#' @param NonResponse .
#' @param LimitRange .
#' @param RangeMin .
#' @param RangeMax .
#' @param Cheating .
#' @param CheatingAttempts .
#' @param ReplicationOn .
#' @param ReplicationPower .
#' @param ReplicationPrior .
#' @param ReplicationAttempts .
#' @param ReplicationDecision .
#' @param ReplicationAlpha .
#' @param ReplicationSign .
#' @param ReplicationSigOriginal .
#' @param alphaSig .
#' @param ssq .
#' @param interaction .
#' @param equalVar .
#' @param Transform .
#' @param likelihoodType .
#' @param likelihoodCutaway .
#' @param likelihoodUsePrior .
#' @param priorPDF .
#' @param priorRZ .
#' @param priorLambda .
#' @param priorNullP .
#' @param MetaAnalysisOn .
#' @param MetaAnalysisType .
#' @param MetaAnalysisNulls .
#' @param MetaAnalysisBias .
#' @param MetaAnalysisNStudies .
#' @param MetaAnalysisStudiesSig .
#' @param showHypothesisBtn .
#' @param showHypothesisType .
#' @param makeSampleBtn .
#' @param numberSamples .
#' @param makeMultipleBtn .
#' @param singleVar1 .
#' @param singleVar2 .
#' @param multipleVar1 .
#' @param multipleVar2 .
#' @param showSampleType .
#' @param showInferParam .
#' @param showInferDimension .
#' @param showMultipleParam .
#' @param showMultipleDimension .
#' @param exploreNPointsH .
#' @param exploreNPointsD .
#' @param exploreNPointsA .
#' @param exploreNPointsM .
#' @param exploreMinValH .
#' @param exploreMaxValH .
#' @param exploreMinValD .
#' @param exploreMaxValD .
#' @param exploreMinValA .
#' @param exploreMaxValM .
#' @param exploreMinValM .
#' @param exploreMaxValA .
#' @param exploreXLogH .
#' @param exploreXLogD .
#' @param exploreXLogA .
#' @param exploreXLogM .
#' @param numberExplores .
#' @param makeExploreBtn .
#' @param exploreMode .
#' @param hypothesisExploreList .
#' @param designExploreList .
#' @param analysisExploreList .
#' @param moreExploreList .
#' @param showExploreParam .
#' @param exploreVar1 .
#' @param exploreVar2 .
#' @param showExploreDimension .
#' @param whichShowMultiple .
#' @param showJamovi .
#' @param showHTML .
#' @param doProject1aBtn .
#' @param doProject1bBtn .
#' @param doProject1cBtn .
#' @param doProject1dBtn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$testHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$BrawStatsInstructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$graphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$JamoviInstructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sendSample} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendMultiple} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
BrawSim <- function(
    planOptions,
    presetDV = "Blank",
    presetIV = "Blank",
    presetIV2 = "none",
    presetWorld = "simple",
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 0,
    DVnlevs = 7,
    DViqr = 4,
    DVncats = 2,
    DVcases = "C1,C2",
    DVprops = "1,1",
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 0,
    IVnlevs = 7,
    IViqr = 4,
    IVncats = 2,
    IVcases = "C1,C2",
    IVprops = "1,1",
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 0,
    IV2nlevs = 7,
    IV2iqr = 4,
    IV2ncats = 2,
    IV2cases = "C1,C2",
    IV2props = "1,1",
    EffectSize1 = 0,
    EffectSize2 = 0,
    EffectSize3 = 0,
    EffectSize12 = 0,
    Heteroscedasticity = 0,
    Residuals = "normal",
    WorldOn = FALSE,
    WorldPDF = "Single",
    WorldRZ,
    WorldLambda = 0.3,
    WorldNullP = 0.5,
    SampleSize = 42,
    SampleSizeM = 42,
    SampleSpreadOn = FALSE,
    SampleGamma = 1.56,
    SampleMethod = "Random",
    SampleUsage1 = "Between",
    SampleUsage2 = "Between",
    Dependence = 0,
    Outliers = 0,
    NonResponse = 0,
    LimitRange = "no",
    RangeMin = -3,
    RangeMax = 3,
    Cheating = "None",
    CheatingAttempts = 5,
    ReplicationOn = FALSE,
    ReplicationPower = 0.8,
    ReplicationPrior = "None",
    ReplicationAttempts = 1,
    ReplicationDecision = "Cautious",
    ReplicationAlpha = 0.05,
    ReplicationSign = "yes",
    ReplicationSigOriginal = "yes",
    alphaSig = 0.05,
    ssq = "Type3",
    interaction = "no",
    equalVar = "yes",
    Transform = "None",
    likelihoodType = "Populations",
    likelihoodCutaway = "cutaway",
    likelihoodUsePrior = "none",
    priorPDF = "Exp",
    priorRZ = "z",
    priorLambda = 0.3,
    priorNullP = 0,
    MetaAnalysisOn = FALSE,
    MetaAnalysisType = "random",
    MetaAnalysisNulls = "yes",
    MetaAnalysisBias = "yes",
    MetaAnalysisNStudies = 10,
    MetaAnalysisStudiesSig = "sigOnly",
    showHypothesisBtn,
    showHypothesisType = "plan",
    makeSampleBtn = FALSE,
    numberSamples = 100,
    makeMultipleBtn,
    singleVar1 = "rs",
    singleVar2 = "p",
    multipleVar1 = "rs",
    multipleVar2 = "p",
    showSampleType = "Compact",
    showInferParam = "Basic",
    showInferDimension = "1D",
    showMultipleParam = "Basic",
    showMultipleDimension = "1D",
    exploreNPointsH = 13,
    exploreNPointsD = 13,
    exploreNPointsA = 13,
    exploreNPointsM = 13,
    exploreMinValH = "-0.9",
    exploreMaxValH = "0.9",
    exploreMinValD = "10",
    exploreMaxValD = "250",
    exploreMinValA = "0.001",
    exploreMaxValM = "0.5",
    exploreMinValM = "0.001",
    exploreMaxValA = "0.5",
    exploreXLogH = FALSE,
    exploreXLogD = FALSE,
    exploreXLogA = FALSE,
    exploreXLogM = FALSE,
    numberExplores = 50,
    makeExploreBtn,
    exploreMode = "designExplore",
    hypothesisExploreList,
    designExploreList,
    analysisExploreList,
    moreExploreList,
    showExploreParam = "Basic",
    exploreVar1 = "rs",
    exploreVar2 = "p",
    showExploreDimension = "1D",
    whichShowMultiple = "all",
    showJamovi = FALSE,
    showHTML = TRUE,
    doProject1aBtn,
    doProject1bBtn,
    doProject1cBtn,
    doProject1dBtn) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        planOptions = planOptions,
        presetDV = presetDV,
        presetIV = presetIV,
        presetIV2 = presetIV2,
        presetWorld = presetWorld,
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        DVnlevs = DVnlevs,
        DViqr = DViqr,
        DVncats = DVncats,
        DVcases = DVcases,
        DVprops = DVprops,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IVnlevs = IVnlevs,
        IViqr = IViqr,
        IVncats = IVncats,
        IVcases = IVcases,
        IVprops = IVprops,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        IV2nlevs = IV2nlevs,
        IV2iqr = IV2iqr,
        IV2ncats = IV2ncats,
        IV2cases = IV2cases,
        IV2props = IV2props,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        Heteroscedasticity = Heteroscedasticity,
        Residuals = Residuals,
        WorldOn = WorldOn,
        WorldPDF = WorldPDF,
        WorldRZ = WorldRZ,
        WorldLambda = WorldLambda,
        WorldNullP = WorldNullP,
        SampleSize = SampleSize,
        SampleSizeM = SampleSizeM,
        SampleSpreadOn = SampleSpreadOn,
        SampleGamma = SampleGamma,
        SampleMethod = SampleMethod,
        SampleUsage1 = SampleUsage1,
        SampleUsage2 = SampleUsage2,
        Dependence = Dependence,
        Outliers = Outliers,
        NonResponse = NonResponse,
        LimitRange = LimitRange,
        RangeMin = RangeMin,
        RangeMax = RangeMax,
        Cheating = Cheating,
        CheatingAttempts = CheatingAttempts,
        ReplicationOn = ReplicationOn,
        ReplicationPower = ReplicationPower,
        ReplicationPrior = ReplicationPrior,
        ReplicationAttempts = ReplicationAttempts,
        ReplicationDecision = ReplicationDecision,
        ReplicationAlpha = ReplicationAlpha,
        ReplicationSign = ReplicationSign,
        ReplicationSigOriginal = ReplicationSigOriginal,
        alphaSig = alphaSig,
        ssq = ssq,
        interaction = interaction,
        equalVar = equalVar,
        Transform = Transform,
        likelihoodType = likelihoodType,
        likelihoodCutaway = likelihoodCutaway,
        likelihoodUsePrior = likelihoodUsePrior,
        priorPDF = priorPDF,
        priorRZ = priorRZ,
        priorLambda = priorLambda,
        priorNullP = priorNullP,
        MetaAnalysisOn = MetaAnalysisOn,
        MetaAnalysisType = MetaAnalysisType,
        MetaAnalysisNulls = MetaAnalysisNulls,
        MetaAnalysisBias = MetaAnalysisBias,
        MetaAnalysisNStudies = MetaAnalysisNStudies,
        MetaAnalysisStudiesSig = MetaAnalysisStudiesSig,
        showHypothesisBtn = showHypothesisBtn,
        showHypothesisType = showHypothesisType,
        makeSampleBtn = makeSampleBtn,
        numberSamples = numberSamples,
        makeMultipleBtn = makeMultipleBtn,
        singleVar1 = singleVar1,
        singleVar2 = singleVar2,
        multipleVar1 = multipleVar1,
        multipleVar2 = multipleVar2,
        showSampleType = showSampleType,
        showInferParam = showInferParam,
        showInferDimension = showInferDimension,
        showMultipleParam = showMultipleParam,
        showMultipleDimension = showMultipleDimension,
        exploreNPointsH = exploreNPointsH,
        exploreNPointsD = exploreNPointsD,
        exploreNPointsA = exploreNPointsA,
        exploreNPointsM = exploreNPointsM,
        exploreMinValH = exploreMinValH,
        exploreMaxValH = exploreMaxValH,
        exploreMinValD = exploreMinValD,
        exploreMaxValD = exploreMaxValD,
        exploreMinValA = exploreMinValA,
        exploreMaxValM = exploreMaxValM,
        exploreMinValM = exploreMinValM,
        exploreMaxValA = exploreMaxValA,
        exploreXLogH = exploreXLogH,
        exploreXLogD = exploreXLogD,
        exploreXLogA = exploreXLogA,
        exploreXLogM = exploreXLogM,
        numberExplores = numberExplores,
        makeExploreBtn = makeExploreBtn,
        exploreMode = exploreMode,
        hypothesisExploreList = hypothesisExploreList,
        designExploreList = designExploreList,
        analysisExploreList = analysisExploreList,
        moreExploreList = moreExploreList,
        showExploreParam = showExploreParam,
        exploreVar1 = exploreVar1,
        exploreVar2 = exploreVar2,
        showExploreDimension = showExploreDimension,
        whichShowMultiple = whichShowMultiple,
        showJamovi = showJamovi,
        showHTML = showHTML,
        doProject1aBtn = doProject1aBtn,
        doProject1bBtn = doProject1bBtn,
        doProject1cBtn = doProject1cBtn,
        doProject1dBtn = doProject1dBtn)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

